import type {
  BlenderCommandPlan,
  BlenderRunState,
  SceneEvidence,
  SceneSpec,
  SourceCandidate,
  TinyFishCapabilityProfile,
} from "./contracts.js";

export const productLine =
  "Codex conducts the web. TinyFish researches the mess. Blender receives a grounded scene.";

export const tinyFishCapabilityProfile: TinyFishCapabilityProfile = {
  name: "TinyFish Web Agent",
  docs_url: "https://docs.tinyfish.ai/",
  api_base: "https://agent.tinyfish.ai",
  primary_endpoint: "/v1/automation/run-sse",
  browser_profiles: [
    {
      id: "lite",
      label: "Lite browser",
      best_for: "Fast public pages, docs, and simple JS flows where stealth is unnecessary.",
    },
    {
      id: "stealth",
      label: "Stealth browser",
      best_for: "Protected or suspicious surfaces where bot-sensitive navigation is likely.",
    },
  ],
  event_types: ["STARTED", "STREAMING_URL", "PROGRESS", "HEARTBEAT", "COMPLETE"],
  constraints: [
    "run-sse returns a text/event-stream and may include a streaming browser URL",
    "use lite before stealth unless the page is blocked or highly interactive",
    "vault credentials and credential_item_ids are optional and should stay off for public-web demos",
    "proxy_config is optional and only needed for geo-specific browsing",
  ],
  example_goal_templates: [
    "Research public sources about a cinematic topic and return strict JSON only.",
    "Find visual motifs, spatial relationships, lighting cues, and camera ideas with citations.",
    "Extract scene-relevant data conservatively and lower confidence when unsure.",
  ],
};

export const defaultResearchSources: SourceCandidate[] = [
  {
    id: "tinyfish-run-sse",
    title: "TinyFish run-sse endpoint",
    url: "https://docs.tinyfish.ai/api-reference/automation/run-browser-automation-with-sse-streaming",
    kind: "api",
    requires_browser: false,
    recommended_browser_mode: "none",
    reason: "Ground truth for the live streaming automation contract that Codex will explain in the demo.",
  },
  {
    id: "tinyfish-home",
    title: "TinyFish documentation home",
    url: "https://docs.tinyfish.ai/",
    kind: "docs",
    requires_browser: false,
    recommended_browser_mode: "none",
    reason: "Docs-level positioning, capabilities, and examples for the research lane.",
  },
  {
    id: "blender-cameras",
    title: "Blender camera manual",
    url: "https://docs.blender.org/manual/en/latest/render/cameras.html",
    kind: "manual",
    requires_browser: false,
    recommended_browser_mode: "none",
    reason: "Useful grounding for hero framing, lens feel, and supporting shots.",
  },
  {
    id: "blender-lights",
    title: "Blender lighting manual",
    url: "https://docs.blender.org/manual/en/latest/render/lights/introduction.html",
    kind: "manual",
    requires_browser: false,
    recommended_browser_mode: "none",
    reason: "Operator-facing reminder for readable cinematic blocking and light roles.",
  },
  {
    id: "blender-collections",
    title: "Blender collections manual",
    url: "https://docs.blender.org/manual/en/latest/scene_layout/collections/introduction.html",
    kind: "manual",
    requires_browser: false,
    recommended_browser_mode: "none",
    reason: "Backing material for deterministic collection layout in the downstream Blender plan.",
  },
  {
    id: "indie-burnout-moodboard",
    title: "Late-night indie artist moodboard",
    url: "https://www.blender.org/features/",
    kind: "moodboard",
    requires_browser: true,
    recommended_browser_mode: "lite",
    reason: "Useful as a public visual anchor when the prompt wants studio atmosphere rather than API detail.",
  },
];

export const defaultGoal =
  "Build a cinematic previs scene about the hidden struggles of indie 3D artists and show how Codex researches it before Blender blocks it out.";

export const demoEvidence: SceneEvidence[] = [
  {
    id: "e-run-sse",
    label: "TinyFish streaming contract",
    url: "https://docs.tinyfish.ai/api-reference/automation/run-browser-automation-with-sse-streaming",
    snippet: "run-sse returns SSE events including STARTED, STREAMING_URL, PROGRESS, COMPLETE, plus heartbeats.",
    source_kind: "api",
  },
  {
    id: "e-lite-stealth",
    label: "TinyFish browser profiles",
    url: "https://docs.tinyfish.ai/api-reference/automation/run-browser-automation-with-sse-streaming",
    snippet: "TinyFish exposes lite and stealth browser profiles depending on page sensitivity.",
    source_kind: "api",
  },
  {
    id: "e-camera",
    label: "Blender camera grounding",
    url: "https://docs.blender.org/manual/en/latest/render/cameras.html",
    snippet: "Camera choice and framing determine how the scene reads emotionally and spatially.",
    source_kind: "manual",
  },
  {
    id: "e-light",
    label: "Blender lighting grounding",
    url: "https://docs.blender.org/manual/en/latest/render/lights/introduction.html",
    snippet: "Readable light roles keep previs scenes legible even with simple geometry.",
    source_kind: "manual",
  },
  {
    id: "e-collections",
    label: "Collections organization",
    url: "https://docs.blender.org/manual/en/latest/scene_layout/collections/introduction.html",
    snippet: "Collections help organize scene elements into deterministic groups for production workflows.",
    source_kind: "manual",
  },
];

export const demoSceneSpec: SceneSpec = {
  scene_id: "scene-indie-artist",
  project_title: "The Cost of the First Frame",
  topic: "Hidden struggles of indie 3D artists",
  scene_goal:
    "Block out a grounded previs scene that visualizes rendering bottlenecks, rigging pain, lighting complexity, and burnout in one coherent late-night studio.",
  style_keywords: ["cinematic", "late-night", "melancholic", "industrial", "grounded"],
  environment: {
    location_type: "small studio loft",
    time_of_day: "02:17 AM",
    weather: "humid city rain outside the windows",
    mood: "focused but frayed",
    scale: "single-room hero set with layered desk depth",
  },
  objects: [
    {
      id: "obj-workstation",
      name: "Overworked workstation",
      category: "setpiece",
      description: "A battered desk with dual monitors, a tower case, and visible render tiles on screen.",
      material: "powder-coated metal, plastic, glass",
      color: "graphite with tired blue screen glow",
      approx_size: "2m x 1m",
      placement_hint: "center-left, angled toward the hero camera",
      importance: 5,
      confidence: 0.96,
      citations: [demoEvidence[0], demoEvidence[3]],
    },
    {
      id: "obj-rig",
      name: "Rigging mannequin",
      category: "character",
      description: "A half-rigged stand-in character posed like an unresolved production note.",
      material: "matte clay with wireframe accents",
      color: "warm grey",
      approx_size: "human scale",
      placement_hint: "mid-ground near the workstation",
      importance: 4,
      confidence: 0.88,
      citations: [demoEvidence[2]],
    },
    {
      id: "obj-cables",
      name: "Cable nest",
      category: "prop",
      description: "Visible cable loops and adapters that imply pipeline complexity and constant reconfiguration.",
      material: "rubber, braided nylon, dusty metal",
      color: "charcoal and signal orange",
      approx_size: "floor spread",
      placement_hint: "foreground crossing the red axis of the room",
      importance: 3,
      confidence: 0.83,
      citations: [demoEvidence[4]],
    },
    {
      id: "obj-countdown",
      name: "Deadline countdown",
      category: "fx",
      description: "A bright phone or tablet timer used as a practical light and symbolic stress beacon.",
      material: "glass and anodized aluminum",
      color: "amber-white",
      approx_size: "handheld",
      placement_hint: "on the desk edge nearest the camera",
      importance: 4,
      confidence: 0.76,
      citations: [demoEvidence[3]],
    },
    {
      id: "obj-notes",
      name: "Pinned revision notes",
      category: "note",
      description: "Annotations showing unresolved scene elements, perf limits, and missing asset polish.",
      material: "paper, tape, cork board",
      color: "muted yellow",
      approx_size: "wall patch",
      placement_hint: "back wall behind the workstation",
      importance: 2,
      confidence: 0.8,
      citations: [demoEvidence[1]],
    },
  ],
  camera: {
    shot_type: "hero medium-wide",
    lens_feel: "35mm documentary with shallow emotional isolation",
    framing_notes: "Desk and mannequin dominate the frame, with the countdown light as a secondary focal point. Add two support shots: over-shoulder and profile close-up.",
  },
  lighting: {
    key_light: "cool monitor spill from the workstation screens",
    fill_light: "weak overhead practical bounced from the desk",
    rim_light: "thin rainy window edge from camera right",
    practicals: ["deadline countdown device", "tower case LEDs", "distant corridor spill"],
    overall_feel: "low-key, readable, and slightly oppressive",
  },
  animation_cues: [
    "slow camera drift toward the workstation",
    "subtle blinking render progress bars",
    "very minor mannequin sway for unease",
  ],
  composition_rules: [
    "keep the workstation as the visual anchor",
    "use cables to drag the eye through the foreground",
    "reserve the brightest practical for deadline pressure",
  ],
  must_include: ["workstation", "rigging mannequin", "deadline countdown"],
  avoid: ["finished hero assets", "over-designed cyberpunk clutter", "clean corporate office lighting"],
  citations: demoEvidence,
};

export const demoBlenderCommandPlan: BlenderCommandPlan = {
  scene_id: demoSceneSpec.scene_id,
  summary: "Create deterministic collections, block the room, place hero props, add readable lights, and frame three cameras.",
  notes: [
    "Use primitives and empties for all unresolved assets.",
    "Keep the scene editable and low-risk for live demo playback.",
    "Annotations should preserve uncertainty instead of inventing final art.",
  ],
  actions: [
    {
      id: "act-env",
      kind: "collection",
      label: "Create base collections",
      detail: "Create ENV, PROPS, CHARACTERS, LIGHTS, CAMERAS, and NOTES collections.",
      command: "collections.create(['ENV','PROPS','CHARACTERS','LIGHTS','CAMERAS','NOTES'])",
      target_node_ids: ["obj-workstation", "obj-rig", "obj-countdown"],
      status: "pending",
    },
    {
      id: "act-room",
      kind: "mesh",
      label: "Block studio shell",
      detail: "Create the loft room and window openings using simple planes and cubes.",
      command: "mesh.blockRoom('small studio loft')",
      target_node_ids: [],
      status: "pending",
    },
    {
      id: "act-cam",
      kind: "camera",
      label: "Stage hero and support cameras",
      detail: "Build one hero camera and two support shots from the framing notes.",
      command: "camera.createHeroAndSupportShots()",
      target_node_ids: [],
      status: "pending",
    },
    {
      id: "act-light",
      kind: "light",
      label: "Establish cinematic lighting",
      detail: "Create monitor key, soft fill, window rim, and practical accents.",
      command: "lights.createLowKeyRig()",
      target_node_ids: ["obj-countdown"],
      status: "pending",
    },
    {
      id: "act-notes",
      kind: "annotation",
      label: "Attach unresolved notes",
      detail: "Add empties or text notes for anything still uncertain after validation.",
      command: "notes.attachUnresolvedAnnotations()",
      target_node_ids: ["obj-notes"],
      status: "pending",
    },
  ],
};

export const demoBlenderState: BlenderRunState = {
  bridge_mode: "fallback",
  status: "idle",
  endpoint_configured: false,
  summary: "Live bridge not configured yet. Fallback export remains available.",
  last_applied_at: null,
  command_plan: demoBlenderCommandPlan,
};
