import type {
  EvalResult,
  SkillRecord,
  SourceCandidate,
  SurfaceSpec,
} from "./contracts.js";

export const productLine = "From pages to procedures. From procedures to software.";

export const seedSources: SourceCandidate[] = [
  {
    id: "tinyfish-repo",
    title: "TinyFish GitHub repository",
    url: "https://github.com/Arnie016/TinyFish",
    kind: "github",
    requiresBrowser: false,
    browserMode: "none",
    reason: "Ground truth for the hackathon codebase and a natural discovery seed.",
  },
  {
    id: "apps-sdk-quickstart",
    title: "OpenAI Apps SDK quickstart",
    url: "https://developers.openai.com/apps-sdk/quickstart",
    kind: "docs",
    requiresBrowser: false,
    browserMode: "none",
    reason: "Current setup guidance for ChatGPT-compatible MCP apps and widgets.",
  },
  {
    id: "apps-sdk-mcp-server",
    title: "OpenAI Apps SDK build MCP server",
    url: "https://developers.openai.com/apps-sdk/build/mcp-server",
    kind: "docs",
    requiresBrowser: false,
    browserMode: "none",
    reason: "Reference material for the tool layer and resource wiring.",
  },
  {
    id: "mcp-ext-apps",
    title: "MCP Apps examples",
    url: "https://github.com/modelcontextprotocol/ext-apps",
    kind: "github",
    requiresBrowser: false,
    browserMode: "none",
    reason: "Low-friction example bank for the widget and bridge pattern.",
  },
  {
    id: "apps-sdk-examples",
    title: "OpenAI Apps SDK examples",
    url: "https://developers.openai.com/apps-sdk/build/examples",
    kind: "docs",
    requiresBrowser: false,
    browserMode: "none",
    reason: "Official examples for tool planning and UI pairing.",
  },
  {
    id: "public-demo-pages",
    title: "Public demo pages",
    url: "https://developers.openai.com/",
    kind: "demo",
    requiresBrowser: true,
    browserMode: "lite",
    reason: "Judge-visible flows and JS-heavy pages are where TinyFish should step in.",
  },
];

export const seedSkills: SkillRecord[] = [
  {
    skill_id: "radar-browser-lens",
    name: "Radar Browser Lens",
    description: "Escalates from cheap fetches to live browser extraction only when public pages turn dynamic or judge-visible.",
    category: "Browser Automation",
    tags: ["browser-automation", "documentation", "mcp", "workflow-compiler"],
    version: "0.2.1",
    status: "active",
    forked_from: null,
    composed_from: [],
    source_urls: [
      "https://github.com/modelcontextprotocol/ext-apps",
      "https://developers.openai.com/apps-sdk/build/examples",
    ],
    source_hashes: ["lens-a1", "lens-a2"],
    surface_type: "widget",
    usage_count: 11,
    last_used_at: "2026-03-27T18:40:00Z",
    last_scanned_at: "2026-03-27T19:05:00Z",
    last_patched_at: "2026-03-25T09:20:00Z",
    eval_score: 0.87,
  },
  {
    skill_id: "docs-to-tool",
    name: "Docs to Tool",
    description: "Turns public documentation into tool-ready steps, examples, and eval prompts.",
    category: "Documentation",
    tags: ["documentation", "mcp", "typescript", "evals"],
    version: "0.4.2",
    status: "active",
    forked_from: null,
    composed_from: [],
    source_urls: [
      "https://developers.openai.com/apps-sdk/quickstart",
      "https://developers.openai.com/apps-sdk/build/mcp-server",
    ],
    source_hashes: ["docs-b1", "docs-b2"],
    surface_type: "chat",
    usage_count: 34,
    last_used_at: "2026-03-28T02:11:00Z",
    last_scanned_at: "2026-03-27T22:00:00Z",
    last_patched_at: null,
    eval_score: 0.92,
  },
  {
    skill_id: "surface-shell",
    name: "Surface Shell",
    description: "Wraps a reusable skill in a small UI surface such as a widget, menu bar view, or desktop shell.",
    category: "macOS Utility Builders",
    tags: ["swiftui", "widgetkit", "menu-bar", "app-shell"],
    version: "0.3.0",
    status: "active",
    forked_from: null,
    composed_from: [],
    source_urls: [
      "https://developers.openai.com/apps-sdk/build/examples",
      "https://github.com/modelcontextprotocol/ext-apps",
    ],
    source_hashes: ["surface-c1", "surface-c2"],
    surface_type: "menu-bar",
    usage_count: 19,
    last_used_at: "2026-03-27T11:30:00Z",
    last_scanned_at: "2026-03-26T08:00:00Z",
    last_patched_at: "2026-03-20T13:45:00Z",
    eval_score: 0.84,
  },
  {
    skill_id: "source-drift-patcher",
    name: "Source Drift Patcher",
    description: "Detects source drift, opens a patch job, and requires an eval gate before promotion.",
    category: "Documentation",
    tags: ["patch-loop", "changelog", "documentation", "evals"],
    version: "0.5.1",
    status: "active",
    forked_from: null,
    composed_from: [],
    source_urls: [
      "https://developers.openai.com/apps-sdk/build/mcp-server",
      "https://developers.openai.com/apps-sdk/build/examples",
    ],
    source_hashes: ["patch-d1", "patch-d2"],
    surface_type: "widget",
    usage_count: 27,
    last_used_at: "2026-03-26T17:18:00Z",
    last_scanned_at: "2026-03-27T06:10:00Z",
    last_patched_at: "2026-03-27T06:10:00Z",
    eval_score: 0.9,
  },
];

export const seedEvals: EvalResult[] = [
  {
    eval_id: "eval-radar-trigger",
    skill_id: "radar-browser-lens",
    version: "0.2.1",
    round: "trigger",
    prompt: "Extract the public workflow from an interactive docs site and show me the best existing skill to fork.",
    expected_skill: "radar-browser-lens",
    actual_skill: "radar-browser-lens",
    passed: true,
    metrics: {
      trigger_correct: true,
      schema_valid: true,
      source_citation_present: true,
      latency_ms: 1880,
    },
    notes: "Escalated only one dynamic page to TinyFish and kept the rest on cheap fetches.",
  },
  {
    eval_id: "eval-docs-schema",
    skill_id: "docs-to-tool",
    version: "0.4.2",
    round: "schema",
    prompt: "Compile a docs-derived workflow into a skill scaffold with eval prompts.",
    expected_skill: "docs-to-tool",
    actual_skill: "docs-to-tool",
    passed: true,
    metrics: {
      trigger_correct: true,
      schema_valid: true,
      source_citation_present: true,
      latency_ms: 2095,
    },
    notes: "Good schema fidelity and clear step extraction.",
  },
  {
    eval_id: "eval-patch-safety",
    skill_id: "source-drift-patcher",
    version: "0.5.1",
    round: "patch",
    prompt: "Source page changed one selector and one example block. Propose a safe patch job.",
    expected_skill: "source-drift-patcher",
    actual_skill: "source-drift-patcher",
    passed: true,
    metrics: {
      trigger_correct: true,
      schema_valid: true,
      source_citation_present: true,
      latency_ms: 1672,
    },
    notes: "Correctly kept auto-promote disabled and required eval approval.",
  },
];

export const surfacePresets: SurfaceSpec[] = [
  {
    surface_type: "widget",
    display_name: "Radar Registry",
    short_description: "Browse the live skill genome.",
    icon: "radar.svg",
    brand_color: "#FF6B3B",
    default_prompt: "Compile a public docs workflow into a widget-ready skill.",
    quick_actions: ["Render dashboard", "Compile skill", "Patch skill"],
    stats_visible: true,
  },
  {
    surface_type: "chat",
    display_name: "Radar Chat",
    short_description: "Prompt in, procedure out.",
    icon: "chat.svg",
    brand_color: "#0E7C66",
    default_prompt: "What skill should I fork for this public repo workflow?",
    quick_actions: ["Run skill", "Open evidence"],
    stats_visible: false,
  },
];
