import type { SkillRecord, WorkflowSpec, CompilerDecision, PatchJob, RunResult, TinyFishEvent, ExecutionTarget } from './types';

// All 18 skills from https://github.com/Arnie016/codex-goated-skills
// Categories match the repo README groupings
export const SEED_SKILLS: SkillRecord[] = [
  // ═══════════════════════════════════════════════
  // LAUNCH & DISTRIBUTION
  // ═══════════════════════════════════════════════
  {
    skill_id: 'repo-launch',
    name: 'Repo Launch',
    description: 'Scaffold and polish a GitHub-ready project repository. Turns an idea or local project into a clean shareable repo with essential docs, CI, and structure.',
    category: 'Launch & Distribution',
    tags: ['repo', 'github', 'ci', 'setup', 'open-source'],
    version: '0.2.3',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['website-drop', 'content-pack', 'brand-kit'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/repo-launch'],
    source_origin: 'github_trending',
    source_hashes: ['d5f1a8c3'],
    surface_type: 'chat',
    usage_count: 19,
    last_used_at: '2026-03-27T11:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-22T09:00:00Z',
    eval_score: 0.88,
    api_endpoints: [],
    context_snippets: ['gh repo create', 'npx license-generator MIT', 'GitHub Actions CI'],
    extraction_meta: { source_origin: 'github_trending', extracted_at: '2026-03-08T12:00:00Z', tinyfish_run_id: 'tf-run-001', page_count: 2, confidence: 0.88 },
  },
  {
    skill_id: 'website-drop',
    name: 'Website Drop',
    description: 'Audit a local web app, choose the simplest host, and get it to a live URL fast. Preps a site for deploy, confirms the build path, and pushes to Vercel, Netlify, or Cloudflare Pages.',
    category: 'Launch & Distribution',
    tags: ['web', 'deploy', 'hosting', 'vercel', 'ci'],
    version: '0.2.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['repo-launch', 'content-pack'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/website-drop'],
    source_origin: 'hacker_news',
    source_hashes: ['b7d3f5a9'],
    surface_type: 'chat',
    usage_count: 27,
    last_used_at: '2026-03-28T09:45:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-24T18:00:00Z',
    eval_score: 0.89,
    api_endpoints: ['POST /api/deploy', 'GET /api/status'],
    context_snippets: ['vercel deploy --prod', 'netlify deploy --site'],
    extraction_meta: { source_origin: 'hacker_news', extracted_at: '2026-03-12T08:00:00Z', tinyfish_run_id: 'tf-run-002', page_count: 3, confidence: 0.89 },
  },
  {
    skill_id: 'brand-kit',
    name: 'Brand Kit',
    description: 'Create lightweight brand assets and launch metadata for a project. Generates a logo direction, colors, headline, banner ideas, social preview copy, and short positioning text.',
    category: 'Launch & Distribution',
    tags: ['branding', 'design', 'launch', 'identity', 'metadata'],
    version: '0.1.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['content-pack', 'repo-launch'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/brand-kit'],
    source_origin: 'product_hunt',
    source_hashes: ['z1a2b3c4'],
    surface_type: 'chat',
    usage_count: 14,
    last_used_at: '2026-03-26T15:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.84,
    api_endpoints: [],
    context_snippets: ['logo direction', 'brand_color', 'social preview'],
    extraction_meta: { source_origin: 'product_hunt', extracted_at: '2026-03-10T09:00:00Z', tinyfish_run_id: 'tf-run-003', page_count: 1, confidence: 0.84 },
  },
  {
    skill_id: 'content-pack',
    name: 'Content Pack',
    description: 'Turn a project into a compact set of launch-ready copy. Generates taglines, README sections, social posts, release notes, and paste-ready messaging.',
    category: 'Launch & Distribution',
    tags: ['content', 'readme', 'launch', 'marketing', 'docs'],
    version: '0.1.2',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['repo-launch', 'website-drop', 'brand-kit', 'deckdrop-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/content-pack'],
    source_origin: 'product_hunt',
    source_hashes: ['g9l4p2r6'],
    surface_type: 'chat',
    usage_count: 9,
    last_used_at: '2026-03-24T16:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.80,
    api_endpoints: [],
    context_snippets: ['tagline generator', 'README hero section'],
    extraction_meta: { source_origin: 'product_hunt', extracted_at: '2026-03-11T09:00:00Z', tinyfish_run_id: 'tf-run-004', page_count: 1, confidence: 0.80 },
  },

  // ═══════════════════════════════════════════════
  // PRODUCTIVITY & WORKFLOW
  // ═══════════════════════════════════════════════
  {
    skill_id: 'workspace-doctor',
    name: 'Workspace Doctor',
    description: 'Diagnose local workspace readiness and common setup problems. Checks project health, missing tools, auth gaps, environment mismatches, and broken dependencies.',
    category: 'Productivity & Workflow',
    tags: ['macos', 'diagnostic', 'homebrew', 'devtools', 'setup'],
    version: '0.3.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['project-hail-mary', 'network-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/workspace-doctor'],
    source_origin: 'github_trending',
    source_hashes: ['a4c8e1f2'],
    surface_type: 'mcp_tool',
    usage_count: 38,
    last_used_at: '2026-03-27T22:10:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-20T14:00:00Z',
    eval_score: 0.91,
    api_endpoints: [],
    context_snippets: ['brew doctor', 'xcode-select --install', 'nvm ls', 'which node'],
    extraction_meta: { source_origin: 'github_trending', extracted_at: '2026-03-15T10:00:00Z', tinyfish_run_id: 'tf-run-005', page_count: 2, confidence: 0.91 },
  },
  {
    skill_id: 'clipboard-studio',
    name: 'Clipboard Studio',
    description: 'Shape, build, or refine a macOS menu bar clipboard app with searchable history, pinned snippets, smart transforms, and quick paste-back into the editor.',
    category: 'Productivity & Workflow',
    tags: ['macos', 'clipboard', 'menu-bar', 'productivity', 'swiftui'],
    version: '0.2.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['project-hail-mary', 'network-studio', 'folder-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/clipboard-studio'],
    source_origin: 'hacker_news',
    source_hashes: ['h1n5q3s7'],
    surface_type: 'widget',
    usage_count: 22,
    last_used_at: '2026-03-27T19:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-23T11:00:00Z',
    eval_score: 0.90,
    api_endpoints: [],
    context_snippets: ['NSPasteboard', 'UIPasteboard', 'pbcopy', 'MenuBarExtra'],
    extraction_meta: { source_origin: 'hacker_news', extracted_at: '2026-03-09T11:00:00Z', tinyfish_run_id: 'tf-run-006', page_count: 2, confidence: 0.90 },
  },
  {
    skill_id: 'project-hail-mary',
    name: 'Project Hail Mary',
    description: 'Build a macOS rescue launcher and focus ritual: kicks off a hype track, opens critical work surfaces, starts a countdown, and copies a heads-down status update.',
    category: 'Productivity & Workflow',
    tags: ['macos', 'launcher', 'focus', 'automation', 'ritual'],
    version: '0.1.3',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['workspace-doctor', 'clipboard-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/project-hail-mary'],
    source_origin: 'hacker_news',
    source_hashes: ['k8r2u5w9'],
    surface_type: 'mcp_tool',
    usage_count: 16,
    last_used_at: '2026-03-27T08:30:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.86,
    api_endpoints: [],
    context_snippets: ['osascript -e', 'open -a', 'afplay', 'countdown timer'],
    extraction_meta: { source_origin: 'hacker_news', extracted_at: '2026-03-13T07:00:00Z', tinyfish_run_id: 'tf-run-007', page_count: 1, confidence: 0.86 },
  },
  {
    skill_id: 'network-studio',
    name: 'Network Studio',
    description: 'Install or update a macOS local-network device monitor with a SwiftBar menu and browser dashboard. Scans LAN devices, tracks connectivity, and alerts on changes.',
    category: 'Productivity & Workflow',
    tags: ['macos', 'networking', 'swiftbar', 'monitor', 'lan'],
    version: '0.1.4',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['workspace-doctor', 'clipboard-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/network-studio'],
    source_origin: 'github_trending',
    source_hashes: ['c2e9d4b1'],
    surface_type: 'widget',
    usage_count: 15,
    last_used_at: '2026-03-26T17:30:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.85,
    api_endpoints: [],
    context_snippets: ['arp -a', 'networksetup -listallhardwareports', 'SwiftBar plugin'],
    extraction_meta: { source_origin: 'github_trending', extracted_at: '2026-03-10T14:00:00Z', tinyfish_run_id: 'tf-run-008', page_count: 1, confidence: 0.85 },
  },
  {
    skill_id: 'dark-pdf-studio',
    name: 'Dark PDF Studio',
    description: 'Convert PDFs, document files, or images into dark-background reading PDFs with a compact input-to-output workflow. Optimized for late-night reading.',
    category: 'Productivity & Workflow',
    tags: ['pdf', 'conversion', 'dark-mode', 'documents', 'reading'],
    version: '0.1.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['deckdrop-studio', 'content-pack'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/dark-pdf-studio'],
    source_origin: 'reddit',
    source_hashes: ['e8g2h6j4'],
    surface_type: 'mcp_tool',
    usage_count: 11,
    last_used_at: '2026-03-25T21:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.83,
    api_endpoints: [],
    context_snippets: ['ghostscript -sDEVICE=pdfwrite', 'convert -negate', 'pdf2image'],
    extraction_meta: { source_origin: 'reddit', extracted_at: '2026-03-14T20:00:00Z', tinyfish_run_id: 'tf-run-009', page_count: 1, confidence: 0.83 },
  },
  {
    skill_id: 'deckdrop-studio',
    name: 'DeckDrop Studio',
    description: 'Build a macOS slide workflow that turns PDFs, docs, presentations, and image sets into editable PowerPoint decks with layout-aware conversion.',
    category: 'Productivity & Workflow',
    tags: ['slides', 'presentations', 'powerpoint', 'conversion', 'design'],
    version: '0.1.0',
    status: 'draft',
    forked_from: null,
    composed_from: [],
    similar_to: ['dark-pdf-studio', 'content-pack'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/deckdrop-studio'],
    source_origin: 'arxiv',
    source_hashes: ['j2p6t4v8'],
    surface_type: 'chat',
    usage_count: 4,
    last_used_at: '2026-03-23T14:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.76,
    api_endpoints: [],
    context_snippets: ['python-pptx', 'pdf2image', 'slide layout detection'],
    extraction_meta: { source_origin: 'arxiv', extracted_at: '2026-03-18T15:00:00Z', page_count: 1, confidence: 0.76 },
  },

  // ═══════════════════════════════════════════════
  // macOS UTILITY BUILDERS
  // ═══════════════════════════════════════════════
  {
    skill_id: 'find-my-phone-studio',
    name: 'Find My Phone Studio',
    description: 'Build a macOS menu bar phone-finder utility with locate, ring, call, QR pairing, and provider-aware handoff flows for Apple or Google accounts.',
    category: 'macOS Utility Builders',
    tags: ['macos', 'phone', 'finder', 'menu-bar', 'swiftui'],
    version: '0.1.2',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['clipboard-studio', 'folder-studio', 'cursor-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/find-my-phone-studio'],
    source_origin: 'product_hunt',
    source_hashes: ['p1q2r3s4'],
    surface_type: 'widget',
    usage_count: 8,
    last_used_at: '2026-03-25T12:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.81,
    api_endpoints: [],
    context_snippets: ['FindMy API', 'QR pairing flow', 'MenuBarExtra', 'CoreLocation'],
    extraction_meta: { source_origin: 'product_hunt', extracted_at: '2026-03-16T10:00:00Z', tinyfish_run_id: 'tf-run-010', page_count: 2, confidence: 0.81 },
  },
  {
    skill_id: 'cursor-studio',
    name: 'Cursor Studio',
    description: 'Build and refine a macOS cursor-pack planner with preset, slot, and export workflows. Plans custom cursor packs from presets, prompt notes, and hotspot grids.',
    category: 'macOS Utility Builders',
    tags: ['macos', 'cursor', 'design', 'menu-bar', 'customization'],
    version: '0.1.0',
    status: 'draft',
    forked_from: null,
    composed_from: [],
    similar_to: ['folder-studio', 'find-my-phone-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/cursor-studio'],
    source_origin: 'reddit',
    source_hashes: ['t5u6v7w8'],
    surface_type: 'widget',
    usage_count: 3,
    last_used_at: '2026-03-22T20:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.74,
    api_endpoints: [],
    context_snippets: ['NSCursor', 'cursor hotspot', 'cape file export'],
    extraction_meta: { source_origin: 'reddit', extracted_at: '2026-03-19T16:00:00Z', page_count: 1, confidence: 0.74 },
  },
  {
    skill_id: 'folder-studio',
    name: 'Folder Studio',
    description: 'Build a macOS folder-skin app that reads folder context, suggests engravings, colors folders, previews Finder icons with context-aware workflows.',
    category: 'macOS Utility Builders',
    tags: ['macos', 'folder', 'icons', 'finder', 'customization'],
    version: '0.1.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['cursor-studio', 'find-my-phone-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/folder-studio'],
    source_origin: 'github_trending',
    source_hashes: ['x9y0z1a2'],
    surface_type: 'widget',
    usage_count: 6,
    last_used_at: '2026-03-24T10:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.79,
    api_endpoints: [],
    context_snippets: ['NSWorkspace setIcon', 'Finder sidebar', 'folder engraving'],
    extraction_meta: { source_origin: 'github_trending', extracted_at: '2026-03-17T13:00:00Z', tinyfish_run_id: 'tf-run-011', page_count: 1, confidence: 0.79 },
  },

  // ═══════════════════════════════════════════════
  // APP-SPECIFIC SKILLS
  // ═══════════════════════════════════════════════
  {
    skill_id: 'telebar',
    name: 'TeleBar',
    description: 'Build, run, troubleshoot, or extend the TeleBar macOS menu bar app. Telegram control center for inbox management, AI writing assists, and setup flows.',
    category: 'App-Specific',
    tags: ['telegram', 'macos', 'menu-bar', 'ai', 'messaging'],
    version: '0.2.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['vibe-bluetooth', 'clipboard-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/telebar'],
    source_origin: 'hacker_news',
    source_hashes: ['b3c4d5e6'],
    surface_type: 'widget',
    usage_count: 18,
    last_used_at: '2026-03-27T21:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-25T15:00:00Z',
    eval_score: 0.87,
    api_endpoints: ['POST /api/telegram/send', 'GET /api/telegram/inbox'],
    context_snippets: ['Telegram Bot API', 'MenuBarExtra', 'AI writing assist'],
    extraction_meta: { source_origin: 'hacker_news', extracted_at: '2026-03-06T18:00:00Z', tinyfish_run_id: 'tf-run-012', page_count: 3, confidence: 0.87 },
  },
  {
    skill_id: 'vibe-bluetooth',
    name: 'Vibe Bluetooth',
    description: 'Dev skill for the VibeWidget macOS SwiftUI app and widget. Voice-first vibe control with Bluetooth device management and ambient state.',
    category: 'App-Specific',
    tags: ['macos', 'swiftui', 'bluetooth', 'widget', 'vibe'],
    version: '0.1.4',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['telebar', 'network-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/vibe-bluetooth'],
    source_origin: 'github_trending',
    source_hashes: ['f7g8h9i0'],
    surface_type: 'widget',
    usage_count: 10,
    last_used_at: '2026-03-26T22:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.82,
    api_endpoints: [],
    context_snippets: ['CBCentralManager', 'WidgetKit', 'AVAudioSession'],
    extraction_meta: { source_origin: 'github_trending', extracted_at: '2026-03-11T20:00:00Z', tinyfish_run_id: 'tf-run-013', page_count: 2, confidence: 0.82 },
  },

  // ═══════════════════════════════════════════════
  // GAMES & CONSOLES
  // ═══════════════════════════════════════════════
  {
    skill_id: 'xbox-studio',
    name: 'Xbox Studio',
    description: 'Build a controller-first macOS Xbox helper for Bluetooth readiness, controller pairing, cloud gaming, Remote Play, capture imports, and official account flows.',
    category: 'Games & Consoles',
    tags: ['xbox', 'macos', 'bluetooth', 'gaming', 'controller'],
    version: '0.4.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['minecraft-essentials', 'minecraft-skin-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/xbox-studio'],
    source_origin: 'reddit',
    source_hashes: ['f3k7m1n5'],
    surface_type: 'widget',
    usage_count: 32,
    last_used_at: '2026-03-28T01:20:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-27T08:00:00Z',
    eval_score: 0.92,
    api_endpoints: [],
    context_snippets: ['IOBluetoothDevice', 'Xbox Cloud Gaming', 'GCController', 'Remote Play'],
    extraction_meta: { source_origin: 'reddit', extracted_at: '2026-03-05T16:00:00Z', tinyfish_run_id: 'tf-run-014', page_count: 4, confidence: 0.92 },
  },
  {
    skill_id: 'minecraft-essentials',
    name: 'Minecraft Essentials',
    description: 'Install, upgrade, run, migrate, back up, and troubleshoot Minecraft Java servers. Handles Vanilla, Paper, Fabric, and Forge with JVM tuning and world management.',
    category: 'Games & Consoles',
    tags: ['minecraft', 'java', 'server', 'devops', 'gaming'],
    version: '0.2.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    similar_to: ['xbox-studio', 'minecraft-skin-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/minecraft-essentials'],
    source_origin: 'reddit',
    source_hashes: ['l9m3n7o1'],
    surface_type: 'chat',
    usage_count: 21,
    last_used_at: '2026-03-27T23:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-26T10:00:00Z',
    eval_score: 0.87,
    api_endpoints: [],
    context_snippets: ['java -Xmx4G -jar server.jar', 'screen -S minecraft', 'server.properties'],
    extraction_meta: { source_origin: 'reddit', extracted_at: '2026-03-07T19:00:00Z', tinyfish_run_id: 'tf-run-015', page_count: 3, confidence: 0.87 },
  },
  {
    skill_id: 'minecraft-skin-studio',
    name: 'Minecraft Skin Studio',
    description: 'Draft, clean, preview, and register Minecraft Java player skins from prompts or PNG files. Turns a skin idea into a launcher-ready 64x64 texture.',
    category: 'Games & Consoles',
    tags: ['minecraft', 'skins', 'design', 'png', 'gaming'],
    version: '0.1.0',
    status: 'draft',
    forked_from: null,
    composed_from: [],
    similar_to: ['minecraft-essentials', 'xbox-studio'],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills/tree/main/skills/minecraft-skin-studio'],
    source_origin: 'reddit',
    source_hashes: ['m4n5o6p7'],
    surface_type: 'chat',
    usage_count: 5,
    last_used_at: '2026-03-24T18:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.73,
    api_endpoints: [],
    context_snippets: ['64x64 skin texture', 'slim vs classic model', 'Minecraft launcher upload'],
    extraction_meta: { source_origin: 'reddit', extracted_at: '2026-03-20T12:00:00Z', page_count: 1, confidence: 0.73 },
  },
];

export const MOCK_WORKFLOW_SPEC: WorkflowSpec = {
  workflow_id: 'supabase-auth-nextjs-v1',
  title: 'Supabase Auth Setup for Next.js',
  description: 'Set up Supabase authentication in a Next.js application with email/password sign-up, sign-in, and session management using the Supabase SSR package.',
  category: 'Documentation',
  tags: ['auth', 'supabase', 'nextjs', 'setup', 'web'],
  source_urls: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  source_kind: ['docs'],
  source_origin: 'hacker_news',
  input_schema: [
    { name: 'project_name', type: 'string', required: true, description: 'Name of the Next.js project to create' },
  ],
  output_schema: { type: 'object', properties: { project_url: { type: 'string' }, auth_configured: { type: 'boolean' }, env_vars_set: { type: 'boolean' } } },
  steps: [
    { id: 's1', action: 'create', instruction: 'Create a new Supabase project at supabase.com/dashboard and note the project URL and anon key.', expected_output: 'Supabase project URL and API key' },
    { id: 's2', action: 'scaffold', instruction: 'Create a new Next.js app using the Supabase auth template: npx create-next-app -e with-supabase', expected_output: 'Next.js project directory with Supabase template' },
    { id: 's3', action: 'configure', instruction: 'Rename .env.example to .env.local and fill in NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY with your project credentials.', expected_output: 'Environment variables configured' },
    { id: 's4', action: 'verify', instruction: 'Run npm run dev and navigate to localhost:3000. Verify the sign-up and login forms work.', expected_output: 'Working auth flow at localhost:3000' },
  ],
  evidence: [
    { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'Use the Next.js quickstart to get up and running with Supabase Auth.' },
    { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'npx create-next-app -e with-supabase' },
    { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key' },
  ],
  surface_suggestion: 'widget',
  confidence: 0.93,
  api_endpoints: ['POST /auth/v1/signup', 'POST /auth/v1/token', 'GET /auth/v1/user'],
};

export const MOCK_COMPILER_DECISION: CompilerDecision = {
  decision: 'create',
  reason: 'No existing skill covers auth setup workflows. website-drop handles deployment but not authentication. Creating a new skill from the extracted workflow spec.',
  nearest_skills: [
    { skill_id: 'website-drop', score: 0.44 },
    { skill_id: 'repo-launch', score: 0.36 },
    { skill_id: 'workspace-doctor', score: 0.28 },
    { skill_id: 'content-pack', score: 0.21 },
    { skill_id: 'network-studio', score: 0.12 },
  ],
  composed_from: [],
  forked_from: null,
};

export const MOCK_COMPILED_SKILL: SkillRecord = {
  skill_id: 'supabase-auth-setup',
  name: 'Supabase Auth Setup',
  description: 'Set up Supabase authentication in a Next.js application with email/password sign-up, sign-in, and session management.',
  category: 'Launch & Distribution',
  tags: ['auth', 'supabase', 'nextjs', 'setup', 'web'],
  version: '0.1.0',
  status: 'active',
  forked_from: null,
  composed_from: [],
  similar_to: ['website-drop', 'repo-launch'],
  source_urls: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  source_origin: 'hacker_news',
  source_hashes: ['f8e7d6c5'],
  surface_type: 'widget',
  usage_count: 0,
  last_used_at: null,
  last_scanned_at: new Date().toISOString(),
  last_patched_at: null,
  eval_score: null,
  api_endpoints: ['POST /auth/v1/signup', 'POST /auth/v1/token', 'GET /auth/v1/user'],
  context_snippets: ['npx create-next-app -e with-supabase', 'NEXT_PUBLIC_SUPABASE_ANON_KEY'],
  extraction_meta: { source_origin: 'hacker_news', extracted_at: new Date().toISOString(), tinyfish_run_id: 'tf-run-live-001', page_count: 3, confidence: 0.93 },
};

export const MOCK_RUN_RESULT: RunResult = {
  skill_id: 'supabase-auth-setup',
  skill_name: 'Supabase Auth Setup',
  project_name: 'my-saas',
  steps: [
    { number: 1, title: 'Create Supabase Project', detail: 'Go to supabase.com/dashboard and create a new project. Copy the project URL and anon key from Settings > API.', evidence: { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'Create a new Supabase project at supabase.com/dashboard' }, status: 'done' },
    { number: 2, title: 'Scaffold Next.js App', command: 'npx create-next-app -e with-supabase my-saas', detail: 'Creates a new Next.js project using the official Supabase auth template with pre-configured middleware and auth helpers.', evidence: { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'npx create-next-app -e with-supabase' }, status: 'done' },
    { number: 3, title: 'Configure Environment', command: 'cp .env.example .env.local', detail: 'Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local with your project credentials.', evidence: { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key' }, status: 'done' },
    { number: 4, title: 'Verify Auth Flow', command: 'npm run dev', detail: 'Navigate to localhost:3000. Test sign-up with email/password, then sign-in. Verify session persists across page reloads.', evidence: { url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs', snippet: 'Navigate to localhost:3000 to verify the auth flow' }, status: 'done' },
  ],
};

export const MOCK_PATCH_JOB: PatchJob = {
  patch_id: 'patch-001',
  skill_id: 'supabase-auth-setup',
  previous_version: '0.1.0',
  proposed_version: '0.1.1',
  change_type: 'patch',
  source_changed: true,
  changed_sources: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  summary: 'Environment variable name changed in Supabase docs: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY \u2192 NEXT_PUBLIC_SUPABASE_ANON_KEY',
  diff_lines: [
    { type: 'context', content: '## Step 3: Configure Environment' },
    { type: 'removed', content: 'Set NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY in .env.local' },
    { type: 'added', content: 'Set NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local' },
    { type: 'context', content: '' },
    { type: 'context', content: '## Version' },
    { type: 'removed', content: 'version: 0.1.0' },
    { type: 'added', content: 'version: 0.1.1' },
  ],
  auto_promote: false,
  eval_required: true,
  approved: false,
};

export const MOCK_TINYFISH_EVENTS: TinyFishEvent[] = [
  { type: 'STARTED', timestamp: 0, message: 'Run initiated \u2014 launching browser' },
  { type: 'STREAMING_URL', timestamp: 800, message: 'Browser session ready', url: 'https://observe.tinyfish.ai/session/abc123' },
  { type: 'PROGRESS', timestamp: 1600, message: 'Navigating to supabase.com/docs/guides/auth/quickstarts/nextjs' },
  { type: 'PROGRESS', timestamp: 2800, message: 'Page loaded \u2014 closing cookie banner' },
  { type: 'PROGRESS', timestamp: 3600, message: 'Reading main content area' },
  { type: 'PROGRESS', timestamp: 4800, message: 'Found quickstart steps \u2014 extracting structured data' },
  { type: 'PROGRESS', timestamp: 5600, message: 'Following link to authentication reference' },
  { type: 'PROGRESS', timestamp: 6800, message: 'Extracting API endpoint signatures' },
  { type: 'PROGRESS', timestamp: 7600, message: 'Collecting code snippets as evidence' },
  { type: 'PROGRESS', timestamp: 8400, message: 'Building workflow spec JSON' },
  { type: 'HEARTBEAT', timestamp: 9000, message: 'Keepalive' },
  { type: 'COMPLETE', timestamp: 9600, message: 'Extraction complete \u2014 4 steps, 3 evidence, 93% confidence' },
];

export const EXECUTION_TARGETS: ExecutionTarget[] = [
  { id: 'codex', name: 'OpenAI Codex', icon: '\u2B21', description: 'Run as a Codex agent skill with SKILL.md and agents/openai.yaml', available: true, launchUrl: 'codex://skill/' },
  { id: 'claude', name: 'Claude Code', icon: '\u25C8', description: 'Execute via Claude Code CLI with MCP tool binding', available: true, launchUrl: 'claude://mcp/' },
  { id: 'cloud', name: 'Cloud Run', icon: '\u2601', description: 'Deploy as a serverless function on Vercel / Cloudflare Workers', available: false },
  { id: 'local', name: 'Local Shell', icon: '\u25B8', description: 'Execute steps as shell commands in your terminal', available: false },
];

export const SCANNING_STEPS = [
  'Launching browser...',
  'Navigating to supabase.com/docs...',
  'Reading page content...',
  'Following quickstart link...',
  'Extracting API endpoints...',
  'Extracting workflow steps...',
  'Identifying input schemas...',
  'Collecting evidence snippets...',
  'Normalizing to workflow spec...',
  'Calculating confidence score...',
  'Extraction complete.',
];

export const SOURCE_ORIGIN_CONFIG: Record<string, { label: string; color: string; icon: string }> = {
  hacker_news: { label: 'Hacker News', color: '#FF6600', icon: 'Y' },
  github_trending: { label: 'GitHub Trending', color: '#238636', icon: '\u25CE' },
  product_hunt: { label: 'Product Hunt', color: '#DA552F', icon: '\u25B2' },
  arxiv: { label: 'arXiv', color: '#B31B1B', icon: '\u2211' },
  dev_docs: { label: 'Dev Docs', color: '#3B82F6', icon: '\u25C7' },
  reddit: { label: 'Reddit', color: '#FF4500', icon: '\u25C9' },
  manual: { label: 'Manual', color: '#6B7280', icon: '\u270E' },
};

// Category colors for graph clustering
export const CATEGORY_COLORS: Record<string, string> = {
  'Launch & Distribution': '#10B981',
  'Productivity & Workflow': '#3B82F6',
  'macOS Utility Builders': '#F59E0B',
  'App-Specific': '#A855F7',
  'Games & Consoles': '#EF4444',
  'Documentation': '#7C3AED',
};
