import type { SkillRecord, WorkflowSpec, CompilerDecision, PatchJob, RunResult } from './types';

export const SEED_SKILLS: SkillRecord[] = [
  {
    skill_id: 'firebase-auth-setup',
    name: 'Firebase Auth Setup',
    description: 'Set up Firebase Authentication in a Next.js app with email/password and Google OAuth providers.',
    category: 'Documentation',
    tags: ['auth', 'firebase', 'nextjs', 'setup'],
    version: '0.2.1',
    status: 'active',
    forked_from: null,
    composed_from: [],
    source_urls: ['https://firebase.google.com/docs/auth/web/start'],
    source_hashes: ['a1b2c3d4'],
    surface_type: 'widget',
    usage_count: 24,
    last_used_at: '2026-03-27T14:30:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-25T10:00:00Z',
    eval_score: 0.91,
  },
  {
    skill_id: 'nextjs-setup-helper',
    name: 'Next.js Setup Helper',
    description: 'Scaffold and configure a new Next.js project with TypeScript, Tailwind CSS, and recommended defaults.',
    category: 'Documentation',
    tags: ['nextjs', 'setup', 'typescript', 'tailwind'],
    version: '0.3.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    source_urls: ['https://nextjs.org/docs/getting-started/installation'],
    source_hashes: ['e5f6g7h8'],
    surface_type: 'widget',
    usage_count: 41,
    last_used_at: '2026-03-28T08:15:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: '2026-03-26T12:00:00Z',
    eval_score: 0.94,
  },
  {
    skill_id: 'workspace-doctor',
    name: 'Workspace Doctor',
    description: 'Diagnose and fix common macOS developer environment issues: Homebrew, Xcode CLI tools, Node versions, shell config.',
    category: 'macOS Utility',
    tags: ['macos', 'diagnostic', 'homebrew', 'devtools'],
    version: '0.1.0',
    status: 'active',
    forked_from: null,
    composed_from: [],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills'],
    source_hashes: ['i9j0k1l2'],
    surface_type: 'mcp_tool',
    usage_count: 12,
    last_used_at: '2026-03-26T20:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.87,
  },
  {
    skill_id: 'content-pack',
    name: 'Content Pack Builder',
    description: 'Package documentation, READMEs, and guides into a structured content bundle for distribution.',
    category: 'Documentation',
    tags: ['content', 'packaging', 'docs', 'markdown'],
    version: '0.1.2',
    status: 'active',
    forked_from: null,
    composed_from: [],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills'],
    source_hashes: ['m3n4o5p6'],
    surface_type: 'chat',
    usage_count: 7,
    last_used_at: '2026-03-24T16:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.82,
  },
  {
    skill_id: 'repo-launch',
    name: 'Repo Launch Kit',
    description: 'Initialize a new GitHub repository with LICENSE, .gitignore, CI/CD, and issue templates.',
    category: 'Documentation',
    tags: ['repo', 'setup', 'github', 'ci'],
    version: '0.2.0',
    status: 'draft',
    forked_from: null,
    composed_from: [],
    source_urls: ['https://github.com/Arnie016/codex-goated-skills'],
    source_hashes: ['q7r8s9t0'],
    surface_type: 'chat',
    usage_count: 3,
    last_used_at: '2026-03-22T11:00:00Z',
    last_scanned_at: '2026-03-28T06:00:00Z',
    last_patched_at: null,
    eval_score: 0.78,
  },
];

export const MOCK_WORKFLOW_SPEC: WorkflowSpec = {
  workflow_id: 'supabase-auth-nextjs-v1',
  title: 'Supabase Auth Setup for Next.js',
  description:
    'Set up Supabase authentication in a Next.js application with email/password sign-up, sign-in, and session management using the Supabase SSR package.',
  category: 'Documentation',
  tags: ['auth', 'supabase', 'nextjs', 'setup'],
  source_urls: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  source_kind: ['docs'],
  input_schema: [
    { name: 'project_name', type: 'string', required: true, description: 'Name of the Next.js project to create' },
  ],
  output_schema: {
    type: 'object',
    properties: {
      project_url: { type: 'string' },
      auth_configured: { type: 'boolean' },
      env_vars_set: { type: 'boolean' },
    },
  },
  steps: [
    {
      id: 's1',
      action: 'create',
      instruction: 'Create a new Supabase project at supabase.com/dashboard and note the project URL and anon key.',
      expected_output: 'Supabase project URL and API key',
    },
    {
      id: 's2',
      action: 'scaffold',
      instruction: 'Create a new Next.js app using the Supabase auth template: npx create-next-app -e with-supabase',
      expected_output: 'Next.js project directory with Supabase template',
    },
    {
      id: 's3',
      action: 'configure',
      instruction:
        'Rename .env.example to .env.local and fill in NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY with your project credentials.',
      expected_output: 'Environment variables configured',
    },
    {
      id: 's4',
      action: 'verify',
      instruction: 'Run npm run dev and navigate to localhost:3000. Verify the sign-up and login forms work.',
      expected_output: 'Working auth flow at localhost:3000',
    },
  ],
  evidence: [
    {
      url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
      snippet: 'Use the Next.js quickstart to get up and running with Supabase Auth.',
    },
    {
      url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
      snippet: 'npx create-next-app -e with-supabase',
    },
    {
      url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
      snippet: 'NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key',
    },
  ],
  surface_suggestion: 'widget',
  confidence: 0.93,
};

export const MOCK_COMPILER_DECISION: CompilerDecision = {
  decision: 'fork',
  reason:
    'firebase-auth-setup covers the same auth-setup pattern for a different provider. Forking preserves the shared structure while adapting provider-specific steps.',
  nearest_skills: [
    { skill_id: 'firebase-auth-setup', score: 0.81 },
    { skill_id: 'nextjs-setup-helper', score: 0.74 },
    { skill_id: 'content-pack', score: 0.31 },
    { skill_id: 'repo-launch', score: 0.28 },
    { skill_id: 'workspace-doctor', score: 0.22 },
  ],
  composed_from: [],
  forked_from: 'firebase-auth-setup',
};

export const MOCK_COMPILED_SKILL: SkillRecord = {
  skill_id: 'supabase-auth-setup',
  name: 'Supabase Auth Setup',
  description:
    'Set up Supabase authentication in a Next.js application with email/password sign-up, sign-in, and session management.',
  category: 'Documentation',
  tags: ['auth', 'supabase', 'nextjs', 'setup'],
  version: '0.1.0',
  status: 'active',
  forked_from: 'firebase-auth-setup',
  composed_from: [],
  source_urls: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  source_hashes: ['f8e7d6c5'],
  surface_type: 'widget',
  usage_count: 0,
  last_used_at: null,
  last_scanned_at: new Date().toISOString(),
  last_patched_at: null,
  eval_score: null,
};

export const MOCK_RUN_RESULT: RunResult = {
  skill_id: 'supabase-auth-setup',
  skill_name: 'Supabase Auth Setup',
  project_name: 'my-saas',
  steps: [
    {
      number: 1,
      title: 'Create Supabase Project',
      command: undefined,
      detail: 'Go to supabase.com/dashboard and create a new project. Copy the project URL and anon key from Settings → API.',
      evidence: {
        url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
        snippet: 'Create a new Supabase project at supabase.com/dashboard',
      },
      status: 'done',
    },
    {
      number: 2,
      title: 'Scaffold Next.js App',
      command: 'npx create-next-app -e with-supabase my-saas',
      detail: 'Creates a new Next.js project using the official Supabase auth template with pre-configured middleware and auth helpers.',
      evidence: {
        url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
        snippet: 'npx create-next-app -e with-supabase',
      },
      status: 'done',
    },
    {
      number: 3,
      title: 'Configure Environment',
      command: 'cp .env.example .env.local',
      detail: 'Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local with your project credentials.',
      evidence: {
        url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
        snippet: 'NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key',
      },
      status: 'done',
    },
    {
      number: 4,
      title: 'Verify Auth Flow',
      command: 'npm run dev',
      detail: 'Navigate to localhost:3000. Test sign-up with email/password, then sign-in. Verify session persists across page reloads.',
      evidence: {
        url: 'https://supabase.com/docs/guides/auth/quickstarts/nextjs',
        snippet: 'Navigate to localhost:3000 to verify the auth flow',
      },
      status: 'done',
    },
  ],
};

export const MOCK_PATCH_JOB: PatchJob = {
  patch_id: 'patch-001',
  skill_id: 'supabase-auth-setup',
  previous_version: '0.1.0',
  proposed_version: '0.1.1',
  change_type: 'patch',
  source_changed: true,
  changed_sources: ['https://supabase.com/docs/guides/auth/quickstarts/nextjs'],
  summary: 'Environment variable name changed in Supabase docs: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY → NEXT_PUBLIC_SUPABASE_ANON_KEY',
  diff_lines: [
    { type: 'context', content: '## Step 3: Configure Environment' },
    { type: 'removed', content: 'Set NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY in .env.local' },
    { type: 'added', content: 'Set NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local' },
    { type: 'context', content: '' },
    { type: 'context', content: '## Version' },
    { type: 'removed', content: 'version: 0.1.0' },
    { type: 'added', content: 'version: 0.1.1' },
  ],
  auto_promote: false,
  eval_required: true,
  approved: false,
};

export const SCANNING_STEPS = [
  'Launching browser...',
  'Navigating to supabase.com/docs...',
  'Reading page content...',
  'Following quickstart link...',
  'Extracting workflow steps...',
  'Identifying input schemas...',
  'Collecting evidence snippets...',
  'Normalizing to workflow spec...',
  'Calculating confidence score...',
  'Extraction complete.',
];
