import type { SceneMetadata, ResearchSource, TinyFishEvent, Artifact, ValidationResult, PipelineCheckpoint, ContextualTip } from './types';

export const DEMO_TOPIC = 'cyberpunk alleyway at night';

export const MOCK_RESEARCH_SOURCES: ResearchSource[] = [
  {
    id: 'src-1',
    url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
    title: 'Cyberpunk Alley Concept Art — ArtStation',
    snippets: [
      'Narrow corridor between towering megastructures',
      'Neon signage in Japanese and English, wet asphalt reflections',
      'Dense cable runs overhead connecting buildings',
    ],
    tags: ['concept-art', 'neon', 'architecture'],
    confidence: 0.94,
    thumbnail_gradient: ['#ff006a', '#1a0033'],
  },
  {
    id: 'src-2',
    url: 'https://en.wikipedia.org/wiki/Cyberpunk',
    title: 'Cyberpunk — Wikipedia',
    snippets: [
      'High tech, low life aesthetic combining advanced technology with social decay',
      'Rain-soaked streets illuminated by holographic advertisements',
      'Characteristic palette: magenta, cyan, deep purple against black',
    ],
    tags: ['genre', 'aesthetic', 'reference'],
    confidence: 0.88,
    thumbnail_gradient: ['#4466ff', '#0a0a10'],
  },
  {
    id: 'src-3',
    url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes',
    title: 'Neon Lighting in Blender — Blender Guru',
    snippets: [
      'Use emission shaders on thin geometry for neon tube effect',
      'Point lights with falloff 0.5m for localized neon glow',
      'Volumetric fog at 0.02 density for light scattering',
    ],
    tags: ['blender', 'lighting', 'tutorial'],
    confidence: 0.91,
    thumbnail_gradient: ['#00ffaa', '#0a1a10'],
  },
  {
    id: 'src-4',
    url: 'https://cinematography.com/index.php/blade-runner-lighting',
    title: 'Blade Runner Lighting Breakdown',
    snippets: [
      'Key light from above, heavily diffused, warm-to-cool gradient',
      'Rim light separates characters from background, cold blue',
      'Practical neon signs provide motivated in-scene lighting',
    ],
    tags: ['cinematography', 'film-reference', 'lighting'],
    confidence: 0.87,
    thumbnail_gradient: ['#ff6600', '#0a0a30'],
  },
  {
    id: 'src-5',
    url: 'https://www.turbosquid.com/cyberpunk-city-assets',
    title: 'Cyberpunk City Asset Pack — TurboSquid',
    snippets: [
      'Modular building sections: 3m, 6m, 9m heights',
      'Standard alley width 4-6 meters for human-scale reference',
      'Common props: dumpsters, AC units, fire escapes, cable bundles',
    ],
    tags: ['3d-assets', 'scale-reference', 'props'],
    confidence: 0.82,
    thumbnail_gradient: ['#7c3aed', '#0a0a10'],
  },
];

export const MOCK_TINYFISH_EVENTS: TinyFishEvent[] = [
  { type: 'STARTED', timestamp: 0, message: 'Run initiated — launching browser' },
  { type: 'STREAMING_URL', timestamp: 600, message: 'Browser session ready', url: 'https://observe.tinyfish.ai/session/fc-001' },
  { type: 'PROGRESS', timestamp: 1800, message: 'Navigating to artstation.com/artwork/cyberpunk-alley-concept' },
  { type: 'PROGRESS', timestamp: 3200, message: 'Page loaded — extracting visual reference data' },
  { type: 'PROGRESS', timestamp: 4600, message: 'Found 12 concept art images — analyzing composition' },
  { type: 'PROGRESS', timestamp: 6000, message: 'Navigating to wikipedia.org/wiki/Cyberpunk' },
  { type: 'PROGRESS', timestamp: 7400, message: 'Extracting genre aesthetics and color palette info' },
  { type: 'PROGRESS', timestamp: 8800, message: 'Navigating to blenderguru.com — lighting reference' },
  { type: 'PROGRESS', timestamp: 10200, message: 'Extracting Blender-specific lighting parameters' },
  { type: 'PROGRESS', timestamp: 11600, message: 'Visiting cinematography.com — Blade Runner breakdown' },
  { type: 'PROGRESS', timestamp: 13000, message: 'Extracting camera and lighting techniques' },
  { type: 'PROGRESS', timestamp: 14400, message: 'Navigating to turbosquid.com — asset scale reference' },
  { type: 'PROGRESS', timestamp: 15800, message: 'Extracting prop dimensions and placement data' },
  { type: 'HEARTBEAT', timestamp: 16500, message: 'Keepalive' },
  { type: 'PROGRESS', timestamp: 17200, message: 'Compiling scene metadata from 5 sources' },
  { type: 'COMPLETE', timestamp: 18000, message: 'Research complete — 14 objects, 5 lights, 5 sources, 89% avg confidence' },
];

export const MOCK_SCENE_METADATA: SceneMetadata = {
  project_title: 'Cyberpunk Alleyway',
  topic: 'cyberpunk alleyway at night',
  scene_goal: 'Moody, neon-lit back alley for a cinematic establishing shot',
  style_keywords: ['cyberpunk', 'noir', 'neon', 'rain', 'dystopian'],
  environment: {
    location_type: 'Urban back alley',
    time_of_day: 'Night',
    weather: 'Light rain, fog',
    mood: 'Brooding, tense, atmospheric',
    scale: '4m wide x 15m deep x 8m tall',
  },
  objects: [
    {
      id: 'obj-wall-left',
      name: 'Left Building Wall',
      category: 'setpiece',
      description: 'Towering concrete wall with exposed pipes and rust stains',
      material: 'Concrete, weathered',
      color: '#1a1a2e',
      approx_size: '1m x 6m x 12m',
      placement_hint: 'Left boundary of alley',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.95,
      position: [-4, 3, 0],
      scale: [1, 6, 12],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', confidence: 0.95 },
      performance: { polyCount: 4200, textureMemoryMB: 2.1, suggestLOD: false },
    },
    {
      id: 'obj-wall-right',
      name: 'Right Building Wall',
      category: 'setpiece',
      description: 'Shorter building with metal cladding and ventilation ducts',
      material: 'Metal cladding, painted',
      color: '#16213e',
      approx_size: '1m x 5m x 12m',
      placement_hint: 'Right boundary of alley',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.95,
      position: [4, 2.5, 0],
      scale: [1, 5, 12],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', confidence: 0.95 },
      performance: { polyCount: 3800, textureMemoryMB: 2.4, suggestLOD: false },
    },
    {
      id: 'obj-ground',
      name: 'Alley Floor',
      category: 'setpiece',
      description: 'Wet asphalt with puddle reflections and cracks',
      material: 'Asphalt, wet',
      color: '#0f0f1a',
      approx_size: '8m x 15m',
      placement_hint: 'Ground plane',
      importance: 5,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.92,
      position: [0, -0.01, 0],
      scale: [8, 0.05, 15],
      geometry: 'box',
      provenance: { sourceType: 'manual', license: 'CC0', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.92 },
      performance: { polyCount: 200, textureMemoryMB: 4.0, suggestLOD: false },
    },
    {
      id: 'obj-dumpster',
      name: 'Dumpster',
      category: 'prop',
      description: 'Rusted green dumpster, lid half-open, overflowing',
      material: 'Painted metal, rusted',
      color: '#2d4a22',
      approx_size: '1.2m x 1m x 0.8m',
      placement_hint: 'Left side, mid-alley',
      importance: 3,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.88,
      position: [-2.5, 0.5, 3],
      scale: [1.2, 1, 0.8],
      geometry: 'box',
      provenance: { sourceType: 'scan', license: 'CC-BY', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.88 },
      performance: { polyCount: 8400, textureMemoryMB: 4.2, suggestLOD: true },
    },
    {
      id: 'obj-neon-ramen',
      name: 'Neon Sign "RAMEN"',
      category: 'prop',
      description: 'Flickering pink neon sign mounted on left wall',
      material: 'Neon glass tubing, emissive',
      color: '#ff006a',
      approx_size: '1.5m x 0.4m x 0.1m',
      placement_hint: 'Left wall, high',
      importance: 4,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.93,
      position: [-3.4, 3.5, 1],
      scale: [1.5, 0.4, 0.1],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'CC0', sourceUrl: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', confidence: 0.93 },
      performance: { polyCount: 1200, textureMemoryMB: 0.5, suggestLOD: false },
    },
    {
      id: 'obj-neon-bar',
      name: 'Neon Sign "BAR"',
      category: 'prop',
      description: 'Cyan neon sign buzzing on right wall',
      material: 'Neon glass tubing, emissive',
      color: '#00ffaa',
      approx_size: '1m x 0.3m x 0.1m',
      placement_hint: 'Right wall, mid-height',
      importance: 4,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.91,
      position: [3.4, 2.8, -2],
      scale: [1, 0.3, 0.1],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'CC0', sourceUrl: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', confidence: 0.91 },
      performance: { polyCount: 980, textureMemoryMB: 0.4, suggestLOD: false },
    },
    {
      id: 'obj-fire-escape',
      name: 'Fire Escape',
      category: 'setpiece',
      description: 'Rusty metal fire escape zigzagging up left wall',
      material: 'Iron, rusted',
      color: '#4a4a5a',
      approx_size: '1.5m x 4m x 0.1m',
      placement_hint: 'Left wall, rear section',
      importance: 3,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.86,
      position: [-3.4, 2, -2],
      scale: [1.5, 4, 0.1],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.86 },
      performance: { polyCount: 12600, textureMemoryMB: 3.8, suggestLOD: true },
    },
    {
      id: 'obj-steam-vent',
      name: 'Steam Vent Pipe',
      category: 'prop',
      description: 'Vertical pipe venting steam, creating atmosphere',
      material: 'Steel pipe',
      color: '#6a6a7a',
      approx_size: '0.15m dia x 2m',
      placement_hint: 'Right side, near entrance',
      importance: 2,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.84,
      position: [2, 1, 4],
      scale: [0.15, 2, 0.15],
      geometry: 'cylinder',
      provenance: { sourceType: 'web-ref', license: 'CC0', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.84 },
      performance: { polyCount: 640, textureMemoryMB: 0.3, suggestLOD: false },
    },
    {
      id: 'obj-motorcycle',
      name: 'Motorcycle',
      category: 'vehicle',
      description: 'Parked motorcycle, dark matte finish, chrome accents',
      material: 'Metal, matte black',
      color: '#1a1a1a',
      approx_size: '0.6m x 0.5m x 1.2m',
      placement_hint: 'Right side, mid-alley',
      importance: 3,
      source_url: 'https://en.wikipedia.org/wiki/Cyberpunk',
      confidence: 0.79,
      position: [2, 0.35, 1],
      scale: [0.6, 0.7, 1.4],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'unknown', sourceUrl: 'https://en.wikipedia.org/wiki/Cyberpunk', confidence: 0.79 },
      performance: { polyCount: 18500, textureMemoryMB: 8.4, suggestLOD: true },
    },
    {
      id: 'obj-puddle',
      name: 'Puddle',
      category: 'fx',
      description: 'Reflective puddle catching neon light',
      material: 'Water, highly reflective',
      color: '#1a1a3a',
      approx_size: '2m x 1.5m',
      placement_hint: 'Center of alley',
      importance: 3,
      source_url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes',
      confidence: 0.87,
      position: [0, 0.01, 1],
      scale: [2.5, 0.02, 2],
      geometry: 'box',
      provenance: { sourceType: 'manual', license: 'CC0', sourceUrl: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes', confidence: 0.87 },
      performance: { polyCount: 100, textureMemoryMB: 1.0, suggestLOD: false },
    },
    {
      id: 'obj-drone',
      name: 'Hovering Drone',
      category: 'vehicle',
      description: 'Small surveillance drone with red indicator light',
      material: 'Matte polymer',
      color: '#3a3a5a',
      approx_size: '0.3m dia',
      placement_hint: 'Above center, high',
      importance: 2,
      source_url: 'https://en.wikipedia.org/wiki/Cyberpunk',
      confidence: 0.76,
      position: [1, 4.5, -1],
      scale: [0.3, 0.15, 0.3],
      geometry: 'sphere',
      provenance: { sourceType: 'ai-gen', license: 'commercial', sourceUrl: 'https://en.wikipedia.org/wiki/Cyberpunk', confidence: 0.76 },
      performance: { polyCount: 6200, textureMemoryMB: 3.2, suggestLOD: false },
    },
    {
      id: 'obj-ac-unit',
      name: 'AC Unit',
      category: 'prop',
      description: 'Window-mounted AC unit dripping condensation',
      material: 'Painted metal',
      color: '#5a5a6a',
      approx_size: '0.8m x 0.6m x 0.4m',
      placement_hint: 'Right wall, high',
      importance: 2,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.83,
      position: [3.4, 3.5, 0],
      scale: [0.8, 0.6, 0.4],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.83 },
      performance: { polyCount: 2400, textureMemoryMB: 1.8, suggestLOD: false },
    },
    {
      id: 'obj-cables',
      name: 'Cable Bundle',
      category: 'setpiece',
      description: 'Dense overhead cable bundle connecting buildings',
      material: 'Rubber-coated wire',
      color: '#2a2a3a',
      approx_size: '8m span',
      placement_hint: 'Overhead, spanning alley',
      importance: 3,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.90,
      position: [0, 5.5, 0],
      scale: [0.08, 0.08, 10],
      geometry: 'cylinder',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', confidence: 0.90 },
      performance: { polyCount: 1800, textureMemoryMB: 0.6, suggestLOD: false },
    },
    {
      id: 'obj-trash',
      name: 'Trash Bags',
      category: 'prop',
      description: 'Black trash bags piled near the dumpster',
      material: 'Plastic, shiny',
      color: '#1a1a1a',
      approx_size: '0.4m x 0.3m',
      placement_hint: 'Near dumpster, ground level',
      importance: 1,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.80,
      position: [-2.5, 0.2, 4],
      scale: [0.5, 0.35, 0.5],
      geometry: 'sphere',
      provenance: { sourceType: 'web-ref', license: 'CC0', sourceUrl: 'https://www.turbosquid.com/cyberpunk-city-assets', confidence: 0.80 },
      performance: { polyCount: 320, textureMemoryMB: 0.2, suggestLOD: false },
    },
  ],
  camera: {
    shot_type: 'Slow dolly through alley',
    lens_feel: 'Wide-angle 24mm, slight barrel distortion',
    framing_notes: 'Low angle, neon signs framing upper third, vanishing point deep in alley',
    path: [
      [0, 2, 8],
      [0.5, 1.8, 4],
      [0, 1.5, 0],
      [-0.5, 1.8, -3],
      [0, 2, -5],
    ],
  },
  lighting: {
    key_light: 'Overhead neon wash — warm pink from RAMEN sign area',
    fill_light: 'Cool blue ambient bounce from right wall',
    rim_light: 'Cold cyan backlight from deep in alley',
    practicals: ['RAMEN neon sign (pink)', 'BAR neon sign (cyan)', 'Drone indicator (red)'],
    overall_feel: 'High contrast, neon-soaked noir — deep shadows with vivid color pools',
    lights: [
      {
        id: 'light-key',
        type: 'key',
        label: 'Overhead Neon',
        color: '#ff006a',
        intensity: 2.0,
        position: [0, 6, 0],
        target: [0, 0, 0],
      },
      {
        id: 'light-fill',
        type: 'fill',
        label: 'Blue Ambient',
        color: '#4466ff',
        intensity: 0.6,
        position: [-3, 3, -4],
      },
      {
        id: 'light-rim',
        type: 'rim',
        label: 'Cold Backlight',
        color: '#00ffaa',
        intensity: 1.5,
        position: [0, 4, -7],
        target: [0, 1, 0],
      },
      {
        id: 'light-practical-1',
        type: 'practical',
        label: 'RAMEN Sign',
        color: '#ff006a',
        intensity: 1.2,
        position: [-3.4, 3.5, 1],
      },
      {
        id: 'light-practical-2',
        type: 'practical',
        label: 'BAR Sign',
        color: '#00ffaa',
        intensity: 0.9,
        position: [3.4, 2.8, -2],
      },
    ],
  },
  color_palette: ['#ff006a', '#00ffaa', '#4466ff', '#1a0033', '#0a0a10', '#6a6a7a', '#ff6600'],
  mood_keywords: ['noir', 'neon-soaked', 'rain-slicked', 'brooding', 'high-contrast', 'cinematic', 'dystopian'],
  composition_rules: [
    'Vanishing point centered in frame',
    'Neon signs frame upper third',
    'Leading lines from building edges guide the eye',
    'Reflections in puddle mirror upper composition',
  ],
  citations: [
    { url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', snippet: 'Narrow corridor between megastructures with neon signage' },
    { url: 'https://en.wikipedia.org/wiki/Cyberpunk', snippet: 'High tech, low life — magenta, cyan, purple against black' },
    { url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes', snippet: 'Emission shaders + point lights + volumetric fog' },
    { url: 'https://cinematography.com/index.php/blade-runner-lighting', snippet: 'Practical neon provides motivated in-scene lighting' },
    { url: 'https://www.turbosquid.com/cyberpunk-city-assets', snippet: 'Modular sections, 4-6m alley width, standard prop set' },
  ],
};

// Artifact bank — items discovered by TinyFish that the user can drag into the scene
export const ARTIFACT_BANK: Artifact[] = [
  // Architecture
  { id: 'a-wall-concrete', name: 'Concrete Wall', category: 'architecture', icon: '\u2588', color: '#4a4a5a', tags: ['structure', 'urban'], relatedIds: ['a-wall-metal', 'a-fire-escape'], gx: 0.12, gy: 0.1 },
  { id: 'a-wall-metal', name: 'Metal Cladding', category: 'architecture', icon: '\u2588', color: '#5a6a7a', tags: ['structure', 'industrial'], relatedIds: ['a-wall-concrete', 'a-ac-unit'], gx: 0.3, gy: 0.08 },
  { id: 'a-fire-escape', name: 'Fire Escape', category: 'architecture', icon: '\u2596', color: '#6a6a7a', tags: ['structure', 'metal'], relatedIds: ['a-wall-concrete', 'a-cables'], gx: 0.08, gy: 0.28 },
  { id: 'a-door-metal', name: 'Metal Door', category: 'architecture', icon: '\u25A3', color: '#3a3a4a', tags: ['structure', 'entry'], relatedIds: ['a-wall-concrete'], gx: 0.22, gy: 0.25 },
  { id: 'a-window', name: 'Barred Window', category: 'architecture', icon: '\u25A4', color: '#2a3a4a', tags: ['structure', 'glass'], relatedIds: ['a-wall-concrete', 'a-ac-unit'], gx: 0.38, gy: 0.22 },
  { id: 'a-cables', name: 'Cable Bundle', category: 'architecture', icon: '\u2261', color: '#2a2a3a', tags: ['overhead', 'wires'], relatedIds: ['a-fire-escape', 'a-wall-metal'], gx: 0.18, gy: 0.42 },

  // Furniture / setpieces
  { id: 'f-dumpster', name: 'Dumpster', category: 'furniture', icon: '\u25A1', color: '#2d4a22', tags: ['container', 'trash'], relatedIds: ['f-trash-bags', 'f-barrel'], gx: 0.55, gy: 0.12 },
  { id: 'f-barrel', name: 'Oil Barrel', category: 'furniture', icon: '\u25CB', color: '#4a3a2a', tags: ['container', 'industrial'], relatedIds: ['f-dumpster', 'f-crate'], gx: 0.7, gy: 0.1 },
  { id: 'f-crate', name: 'Wooden Crate', category: 'furniture', icon: '\u25A0', color: '#5a4a3a', tags: ['container', 'storage'], relatedIds: ['f-barrel', 'f-dumpster'], gx: 0.82, gy: 0.15 },
  { id: 'f-trash-bags', name: 'Trash Bags', category: 'furniture', icon: '\u25CF', color: '#1a1a1a', tags: ['debris', 'ground'], relatedIds: ['f-dumpster'], gx: 0.6, gy: 0.28 },
  { id: 'f-bench', name: 'Metal Bench', category: 'furniture', icon: '\u2550', color: '#5a5a6a', tags: ['seating', 'street'], relatedIds: ['f-crate'], gx: 0.78, gy: 0.3 },

  // Props
  { id: 'p-neon-sign', name: 'Neon Sign', category: 'props', icon: '\u2606', color: '#ff006a', tags: ['light', 'signage', 'emissive'], relatedIds: ['p-neon-kanji', 'l-neon-tube'], gx: 0.15, gy: 0.58 },
  { id: 'p-neon-kanji', name: 'Kanji Sign', category: 'props', icon: '\u5149', color: '#00ffaa', tags: ['light', 'signage', 'emissive'], relatedIds: ['p-neon-sign', 'l-neon-tube'], gx: 0.32, gy: 0.55 },
  { id: 'p-steam-vent', name: 'Steam Vent', category: 'props', icon: '\u2248', color: '#8a8a9a', tags: ['fx', 'atmosphere'], relatedIds: ['p-ac-unit', 'p-manhole'], gx: 0.48, gy: 0.52 },
  { id: 'p-ac-unit', name: 'AC Unit', category: 'props', icon: '\u25A8', color: '#5a5a6a', tags: ['mechanical', 'wall-mount'], relatedIds: ['a-ac-unit', 'p-steam-vent'], gx: 0.42, gy: 0.38 },
  { id: 'p-manhole', name: 'Manhole Cover', category: 'props', icon: '\u25CE', color: '#3a3a4a', tags: ['ground', 'metal'], relatedIds: ['p-steam-vent', 'p-puddle'], gx: 0.58, gy: 0.48 },
  { id: 'p-puddle', name: 'Puddle', category: 'props', icon: '\u223F', color: '#1a1a3a', tags: ['water', 'reflection'], relatedIds: ['p-manhole'], gx: 0.65, gy: 0.58 },
  { id: 'p-poster', name: 'Torn Poster', category: 'props', icon: '\u25AD', color: '#6a4a3a', tags: ['wall', 'paper'], relatedIds: ['p-neon-sign'], gx: 0.25, gy: 0.72 },

  // Vehicles
  { id: 'v-motorcycle', name: 'Motorcycle', category: 'vehicles', icon: '\u25B7', color: '#2a2a2a', tags: ['vehicle', 'parked'], relatedIds: ['v-drone', 'f-barrel'], gx: 0.82, gy: 0.48 },
  { id: 'v-drone', name: 'Hover Drone', category: 'vehicles', icon: '\u25C7', color: '#3a3a5a', tags: ['flying', 'surveillance'], relatedIds: ['v-motorcycle', 'l-spot-red'], gx: 0.9, gy: 0.38 },

  // Environment
  { id: 'e-fog', name: 'Volumetric Fog', category: 'environment', icon: '\u2601', color: '#4a4a6a', tags: ['atmosphere', 'volume'], relatedIds: ['e-rain', 'p-steam-vent'], gx: 0.72, gy: 0.68 },
  { id: 'e-rain', name: 'Rain Particles', category: 'environment', icon: '\u2602', color: '#4a5a7a', tags: ['weather', 'particles'], relatedIds: ['e-fog', 'p-puddle'], gx: 0.85, gy: 0.62 },
  { id: 'e-sky', name: 'Night Sky', category: 'environment', icon: '\u263D', color: '#0a0a2a', tags: ['background', 'dark'], relatedIds: ['e-fog'], gx: 0.92, gy: 0.72 },

  // Lighting
  { id: 'l-neon-tube', name: 'Neon Tube', category: 'lighting', icon: '\u2501', color: '#ff006a', tags: ['emissive', 'practical'], relatedIds: ['p-neon-sign', 'p-neon-kanji'], gx: 0.1, gy: 0.85 },
  { id: 'l-spot-overhead', name: 'Overhead Spot', category: 'lighting', icon: '\u25BD', color: '#ffaa44', tags: ['key', 'directional'], relatedIds: ['l-spot-rim', 'l-neon-tube'], gx: 0.3, gy: 0.88 },
  { id: 'l-spot-rim', name: 'Rim Light', category: 'lighting', icon: '\u25B3', color: '#00ffaa', tags: ['rim', 'backlight'], relatedIds: ['l-spot-overhead'], gx: 0.5, gy: 0.85 },
  { id: 'l-spot-red', name: 'Red Indicator', category: 'lighting', icon: '\u25CF', color: '#ff2222', tags: ['practical', 'warning'], relatedIds: ['v-drone', 'l-neon-tube'], gx: 0.68, gy: 0.82 },
  { id: 'l-ambient', name: 'Blue Ambient', category: 'lighting', icon: '\u25CB', color: '#4466ff', tags: ['fill', 'ambient'], relatedIds: ['l-spot-overhead', 'l-spot-rim'], gx: 0.42, gy: 0.95 },
];

export const ARTIFACT_CATEGORY_COLORS: Record<string, string> = {
  architecture: '#7C3AED',
  furniture: '#06B6D4',
  props: '#EC4899',
  vehicles: '#F59E0B',
  environment: '#10B981',
  lighting: '#FF6B6B',
};

export const SCANNING_STEPS = [
  'Initializing research agent...',
  'Connecting to TinyFish...',
  'Launching browser session...',
  'Searching for visual references...',
  'Visiting artstation.com...',
  'Extracting composition data...',
  'Visiting genre references...',
  'Analyzing lighting techniques...',
  'Gathering asset dimensions...',
  'Compiling scene metadata...',
  'Validating source citations...',
  'Research complete',
];

export const MOCK_VALIDATION_RESULT: ValidationResult = {
  checks: [
    { id: 'v-poly-budget', label: 'Polygon Budget', status: 'pass', detail: '62,400 / 100,000', category: 'geometry' },
    { id: 'v-uv-presence', label: 'UV Maps Present', status: 'pass', detail: '14/14 objects have UVs', category: 'uv' },
    { id: 'v-material-assign', label: 'Material Assignment', status: 'pass', detail: 'All objects have materials', category: 'material' },
    { id: 'v-non-manifold', label: 'Non-Manifold Geometry', status: 'warn', detail: '2 objects with non-manifold edges', category: 'geometry' },
    { id: 'v-tex-resolution', label: 'Texture Resolution', status: 'pass', detail: 'All textures within 2K limit', category: 'texture' },
    { id: 'v-source-citation', label: 'Source Citations', status: 'pass', detail: '14/14 objects have source URLs', category: 'provenance' },
    { id: 'v-license-check', label: 'License Compliance', status: 'warn', detail: '1 object has unknown license', category: 'provenance' },
    { id: 'v-overlap-detect', label: 'Overlapping Faces', status: 'pass', detail: 'No overlapping geometry', category: 'geometry' },
    { id: 'v-tex-memory', label: 'Texture Memory', status: 'pass', detail: '48.2 MB / 256 MB budget', category: 'texture' },
    { id: 'v-scale-uniform', label: 'Scale Consistency', status: 'pass', detail: 'All objects use metric scale', category: 'geometry' },
  ],
  passCount: 8,
  warnCount: 2,
  failCount: 0,
  overallStatus: 'pass',
  timestamp: Date.now(),
};

export const MOCK_PIPELINE_CHECKPOINTS: PipelineCheckpoint[] = [
  { stage: 1, label: 'Raw Scrape', description: 'TinyFish web research', timestamp: null, status: 'pending' },
  { stage: 2, label: 'Validated Spec', description: 'QA checks passed', timestamp: null, status: 'pending' },
  { stage: 3, label: 'Blockout Sent', description: 'Pushed to Blender', timestamp: null, status: 'pending' },
  { stage: 4, label: 'Artist Refinement', description: 'Pending artist review', timestamp: null, status: 'pending' },
];

export const MOCK_CONTEXTUAL_TIPS: ContextualTip[] = [
  { id: 'tip-1', phase: 2, message: 'TinyFish extracts structured data \u2014 every claim needs a source URL', icon: '\uD83D\uDC1F', category: 'research' },
  { id: 'tip-2', phase: 3, message: 'Artifacts with unknown licenses are flagged during validation', icon: '\u26A0\uFE0F', category: 'research' },
  { id: 'tip-3', phase: 4, message: 'SceneSpec validates polygon budgets before sending to Blender', icon: '\u2705', category: 'plan' },
  { id: 'tip-4', phase: 5, message: 'Objects use graybox primitives \u2014 swap for production meshes later', icon: '\uD83D\uDFE8', category: 'build' },
  { id: 'tip-5', phase: 5, message: 'Auto-record can change keyframes unexpectedly \u2014 disable when posing', icon: '\u26A0\uFE0F', category: 'general' },
  { id: 'tip-6', phase: 6, message: 'Practical lights should match visible light sources in scene', icon: '\uD83D\uDCA1', category: 'lighting' },
  { id: 'tip-7', phase: 7, message: 'Camera paths export as Blender animation curves via SceneSpec', icon: '\uD83C\uDFAC', category: 'general' },
  { id: 'tip-8', phase: 8, message: 'All assets tracked: scan/AI/manual/web-ref with license status', icon: '\uD83D\uDCCB', category: 'general' },
];
