import type { SceneMetadata, ResearchSource, TinyFishEvent, Artifact, ValidationResult, PipelineCheckpoint, ContextualTip } from './types';

export const DEMO_TOPIC = 'neon market of lost signals';

export const MOCK_RESEARCH_SOURCES: ResearchSource[] = [
  {
    id: 'src-1',
    url: 'https://www.artstation.com/artwork/neon-night-market-concept',
    title: 'Neon Night Market Concept Art — ArtStation',
    snippets: [
      'Open-air bazaar under tangled signal cables and dead antennas',
      'Vendor stalls draped in holographic tarps, glowing produce crates',
      'Crowds navigating narrow lanes between flickering LED canopies',
    ],
    tags: ['concept-art', 'neon', 'market'],
    confidence: 0.94,
    thumbnail_gradient: ['#ff006a', '#1a0033'],
  },
  {
    id: 'src-2',
    url: 'https://en.wikipedia.org/wiki/Night_market',
    title: 'Night Markets & Signal Culture — Wikipedia',
    snippets: [
      'Street markets operating at night, lit by portable generators and neon strips',
      'Stall density creates maze-like micro-neighborhoods with acoustic dead zones',
      'Lost-signal aesthetic: decommissioned radio towers repurposed as tent poles',
    ],
    tags: ['culture', 'aesthetic', 'reference'],
    confidence: 0.88,
    thumbnail_gradient: ['#4466ff', '#0a0a10'],
  },
  {
    id: 'src-3',
    url: 'https://www.blenderguru.com/tutorials/emissive-market-lighting',
    title: 'Emissive Market Lighting in Blender — Blender Guru',
    snippets: [
      'String lights modeled as emission planes on catenary curves',
      'Area lights inside vendor stalls for warm interior glow',
      'Volumetric haze at 0.015 density catches colored light spill',
    ],
    tags: ['blender', 'lighting', 'tutorial'],
    confidence: 0.91,
    thumbnail_gradient: ['#00ffaa', '#0a1a10'],
  },
  {
    id: 'src-4',
    url: 'https://cinematography.com/index.php/wong-kar-wai-neon',
    title: 'Wong Kar-Wai Neon Palette Breakdown',
    snippets: [
      'Saturated color pools from practical sources — no neutral fill',
      'Faces half-lit by vendor signage, deep shadows on the opposite side',
      'Handheld camera weaving through crowds at shoulder height',
    ],
    tags: ['cinematography', 'film-reference', 'lighting'],
    confidence: 0.87,
    thumbnail_gradient: ['#ff6600', '#0a0a30'],
  },
  {
    id: 'src-5',
    url: 'https://www.turbosquid.com/night-market-props',
    title: 'Night Market Prop Pack — TurboSquid',
    snippets: [
      'Folding table + tarp stall kit: 2m x 1.5m footprint',
      'Antenna mast segments: 0.5m increments, stackable',
      'Common props: lanterns, crate stacks, cable spools, signal dishes',
    ],
    tags: ['3d-assets', 'scale-reference', 'props'],
    confidence: 0.82,
    thumbnail_gradient: ['#7c3aed', '#0a0a10'],
  },
];

export const MOCK_TINYFISH_EVENTS: TinyFishEvent[] = [
  { type: 'STARTED', timestamp: 0, message: 'Run initiated — launching browser' },
  { type: 'STREAMING_URL', timestamp: 600, message: 'Browser session ready', url: 'https://observe.tinyfish.ai/session/fc-001' },
  { type: 'PROGRESS', timestamp: 1800, message: 'Navigating to artstation.com/artwork/neon-night-market-concept' },
  { type: 'PROGRESS', timestamp: 3200, message: 'Page loaded — extracting market layout references' },
  { type: 'PROGRESS', timestamp: 4600, message: 'Found 9 concept art images — analyzing stall compositions' },
  { type: 'PROGRESS', timestamp: 6000, message: 'Navigating to wikipedia.org/wiki/Night_market' },
  { type: 'PROGRESS', timestamp: 7400, message: 'Extracting signal culture aesthetics and layout patterns' },
  { type: 'PROGRESS', timestamp: 8800, message: 'Navigating to blenderguru.com — emissive lighting reference' },
  { type: 'PROGRESS', timestamp: 10200, message: 'Extracting Blender-specific market lighting parameters' },
  { type: 'PROGRESS', timestamp: 11600, message: 'Visiting cinematography.com — Wong Kar-Wai neon breakdown' },
  { type: 'PROGRESS', timestamp: 13000, message: 'Extracting camera and color palette techniques' },
  { type: 'PROGRESS', timestamp: 14400, message: 'Navigating to turbosquid.com — market prop reference' },
  { type: 'PROGRESS', timestamp: 15800, message: 'Extracting stall dimensions and prop placement data' },
  { type: 'HEARTBEAT', timestamp: 16500, message: 'Keepalive' },
  { type: 'PROGRESS', timestamp: 17200, message: 'Compiling scene metadata from 5 sources' },
  { type: 'COMPLETE', timestamp: 18000, message: 'Research complete — 14 objects, 5 lights, 5 sources, 88% avg confidence' },
];

export const MOCK_SCENE_METADATA: SceneMetadata = {
  project_title: 'Neon Market of Lost Signals',
  topic: 'neon market of lost signals',
  scene_goal: 'A buzzing night market built in the shadow of dead signal towers — vendors hawking under tangled antennas and holographic tarps',
  style_keywords: ['neon', 'market', 'lo-fi', 'signal-punk', 'nocturnal'],
  environment: {
    location_type: 'Open-air night market',
    time_of_day: 'Night',
    weather: 'Humid haze, no wind',
    mood: 'Electric, chaotic, intimate',
    scale: '12m wide x 20m deep x 10m tall',
  },
  objects: [
    {
      id: 'obj-stall-left',
      name: 'Tarp Vendor Stall',
      category: 'setpiece',
      description: 'Folding-table stall draped in translucent holographic tarp, warm light spilling out',
      material: 'Aluminum frame, holographic tarp',
      color: '#2a1a3e',
      approx_size: '2m x 1.5m x 2.5m',
      placement_hint: 'Left lane, foreground',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/neon-night-market-concept',
      confidence: 0.95,
      position: [-3, 1.25, 3],
      scale: [2, 2.5, 1.5],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.artstation.com/artwork/neon-night-market-concept', confidence: 0.95 },
      performance: { polyCount: 5200, textureMemoryMB: 2.8, suggestLOD: false },
    },
    {
      id: 'obj-stall-right',
      name: 'Signal Parts Booth',
      category: 'setpiece',
      description: 'Narrow booth crammed with salvaged radio modules, blinking indicator LEDs',
      material: 'Plywood, corrugated metal',
      color: '#1a2a3e',
      approx_size: '1.8m x 1.5m x 2.5m',
      placement_hint: 'Right lane, foreground',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/neon-night-market-concept',
      confidence: 0.93,
      position: [3, 1.25, 2],
      scale: [1.8, 2.5, 1.5],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.artstation.com/artwork/neon-night-market-concept', confidence: 0.93 },
      performance: { polyCount: 4600, textureMemoryMB: 3.1, suggestLOD: false },
    },
    {
      id: 'obj-ground',
      name: 'Market Floor',
      category: 'setpiece',
      description: 'Cracked concrete slab with painted lane markings and puddle stains',
      material: 'Concrete, stained',
      color: '#0f0f1a',
      approx_size: '12m x 20m',
      placement_hint: 'Ground plane',
      importance: 5,
      source_url: 'https://www.turbosquid.com/night-market-props',
      confidence: 0.92,
      position: [0, -0.01, 0],
      scale: [12, 0.05, 20],
      geometry: 'box',
      provenance: { sourceType: 'manual', license: 'CC0', sourceUrl: 'https://www.turbosquid.com/night-market-props', confidence: 0.92 },
      performance: { polyCount: 200, textureMemoryMB: 4.0, suggestLOD: false },
    },
    {
      id: 'obj-antenna-tower',
      name: 'Dead Antenna Tower',
      category: 'setpiece',
      description: 'Decommissioned radio tower, rusted lattice frame, cables dangling from crossarms',
      material: 'Rusted steel lattice',
      color: '#3a2a1a',
      approx_size: '1.5m x 10m x 1.5m',
      placement_hint: 'Center-rear, towering over market',
      importance: 5,
      source_url: 'https://en.wikipedia.org/wiki/Night_market',
      confidence: 0.90,
      position: [0, 5, -6],
      scale: [1.5, 10, 1.5],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://en.wikipedia.org/wiki/Night_market', confidence: 0.90 },
      performance: { polyCount: 8800, textureMemoryMB: 2.4, suggestLOD: true },
    },
    {
      id: 'obj-lantern-string',
      name: 'LED Lantern String',
      category: 'prop',
      description: 'Catenary string of mismatched LED lanterns spanning the lane',
      material: 'Paper, plastic, wire',
      color: '#ff8844',
      approx_size: '8m span x 0.3m',
      placement_hint: 'Overhead, lane center',
      importance: 4,
      source_url: 'https://www.blenderguru.com/tutorials/emissive-market-lighting',
      confidence: 0.91,
      position: [0, 4, 1],
      scale: [8, 0.3, 0.3],
      geometry: 'cylinder',
      provenance: { sourceType: 'web-ref', license: 'CC0', sourceUrl: 'https://www.blenderguru.com/tutorials/emissive-market-lighting', confidence: 0.91 },
      performance: { polyCount: 2400, textureMemoryMB: 1.2, suggestLOD: false },
    },
    {
      id: 'obj-neon-lost',
      name: 'Neon Sign "LOST SIGNALS"',
      category: 'prop',
      description: 'Flickering magenta neon sign bolted to the antenna tower, half the letters dead',
      material: 'Neon glass tubing, emissive',
      color: '#ff006a',
      approx_size: '2m x 0.5m x 0.1m',
      placement_hint: 'Antenna tower, mid-height',
      importance: 4,
      source_url: 'https://www.artstation.com/artwork/neon-night-market-concept',
      confidence: 0.93,
      position: [0.5, 5.5, -5.5],
      scale: [2, 0.5, 0.1],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'CC0', sourceUrl: 'https://www.artstation.com/artwork/neon-night-market-concept', confidence: 0.93 },
      performance: { polyCount: 1400, textureMemoryMB: 0.6, suggestLOD: false },
    },
    {
      id: 'obj-neon-freq',
      name: 'Neon Sign "FREQ"',
      category: 'prop',
      description: 'Cyan neon frequency readout display mounted on right booth',
      material: 'Neon glass tubing, emissive',
      color: '#00ffaa',
      approx_size: '1m x 0.3m x 0.1m',
      placement_hint: 'Right booth, upper edge',
      importance: 3,
      source_url: 'https://www.artstation.com/artwork/neon-night-market-concept',
      confidence: 0.89,
      position: [3.2, 2.8, 1.8],
      scale: [1, 0.3, 0.1],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'CC0', sourceUrl: 'https://www.artstation.com/artwork/neon-night-market-concept', confidence: 0.89 },
      performance: { polyCount: 980, textureMemoryMB: 0.4, suggestLOD: false },
    },
    {
      id: 'obj-crate-stack',
      name: 'Produce Crate Stack',
      category: 'prop',
      description: 'Three stacked plastic crates glowing faintly from bioluminescent produce inside',
      material: 'HDPE plastic, translucent',
      color: '#22aa66',
      approx_size: '0.6m x 0.9m x 0.5m',
      placement_hint: 'Left stall, ground level',
      importance: 3,
      source_url: 'https://www.turbosquid.com/night-market-props',
      confidence: 0.86,
      position: [-2.5, 0.45, 4],
      scale: [0.6, 0.9, 0.5],
      geometry: 'box',
      provenance: { sourceType: 'scan', license: 'CC-BY', sourceUrl: 'https://www.turbosquid.com/night-market-props', confidence: 0.86 },
      performance: { polyCount: 3200, textureMemoryMB: 2.0, suggestLOD: false },
    },
    {
      id: 'obj-signal-dish',
      name: 'Salvaged Satellite Dish',
      category: 'prop',
      description: 'Dented parabolic dish repurposed as a vendor awning',
      material: 'Aluminum, dented',
      color: '#6a6a7a',
      approx_size: '1.8m dia x 0.6m deep',
      placement_hint: 'Left lane, mounted overhead',
      importance: 3,
      source_url: 'https://en.wikipedia.org/wiki/Night_market',
      confidence: 0.84,
      position: [-2, 3.5, 0],
      scale: [1.8, 0.6, 1.8],
      geometry: 'sphere',
      provenance: { sourceType: 'web-ref', license: 'CC0', sourceUrl: 'https://en.wikipedia.org/wiki/Night_market', confidence: 0.84 },
      performance: { polyCount: 4800, textureMemoryMB: 1.8, suggestLOD: false },
    },
    {
      id: 'obj-cable-spool',
      name: 'Cable Spool Table',
      category: 'prop',
      description: 'Large wooden cable spool turned into a makeshift table, drinks on top',
      material: 'Wood, weathered',
      color: '#4a3a2a',
      approx_size: '1.2m dia x 0.7m',
      placement_hint: 'Center lane, seating area',
      importance: 2,
      source_url: 'https://www.turbosquid.com/night-market-props',
      confidence: 0.82,
      position: [0, 0.35, 2],
      scale: [1.2, 0.7, 1.2],
      geometry: 'cylinder',
      provenance: { sourceType: 'web-ref', license: 'CC-BY', sourceUrl: 'https://www.turbosquid.com/night-market-props', confidence: 0.82 },
      performance: { polyCount: 2200, textureMemoryMB: 1.4, suggestLOD: false },
    },
    {
      id: 'obj-generator',
      name: 'Portable Generator',
      category: 'prop',
      description: 'Humming diesel generator powering nearby stalls, exhaust vent visible',
      material: 'Painted steel',
      color: '#3a3a4a',
      approx_size: '0.8m x 0.6m x 0.5m',
      placement_hint: 'Rear-left, behind stalls',
      importance: 2,
      source_url: 'https://www.turbosquid.com/night-market-props',
      confidence: 0.80,
      position: [-4, 0.3, -2],
      scale: [0.8, 0.6, 0.5],
      geometry: 'box',
      provenance: { sourceType: 'web-ref', license: 'CC0', sourceUrl: 'https://www.turbosquid.com/night-market-props', confidence: 0.80 },
      performance: { polyCount: 3400, textureMemoryMB: 2.2, suggestLOD: false },
    },
    {
      id: 'obj-haze',
      name: 'Market Haze',
      category: 'fx',
      description: 'Low-hanging warm haze from cooking smoke and generator exhaust',
      material: 'Volumetric, warm tint',
      color: '#2a1a0a',
      approx_size: '12m x 20m x 3m',
      placement_hint: 'Fills lower half of market',
      importance: 3,
      source_url: 'https://www.blenderguru.com/tutorials/emissive-market-lighting',
      confidence: 0.87,
      position: [0, 1.5, 0],
      scale: [12, 3, 20],
      geometry: 'box',
      provenance: { sourceType: 'manual', license: 'CC0', sourceUrl: 'https://www.blenderguru.com/tutorials/emissive-market-lighting', confidence: 0.87 },
      performance: { polyCount: 100, textureMemoryMB: 0.5, suggestLOD: false },
    },
    {
      id: 'obj-delivery-cart',
      name: 'Delivery Cart',
      category: 'vehicle',
      description: 'Three-wheeled electric delivery cart loaded with signal equipment crates',
      material: 'Sheet metal, matte green',
      color: '#1a3a2a',
      approx_size: '1.5m x 1.2m x 2m',
      placement_hint: 'Right lane, mid-market',
      importance: 3,
      source_url: 'https://en.wikipedia.org/wiki/Night_market',
      confidence: 0.79,
      position: [3, 0.6, -1],
      scale: [1.5, 1.2, 2],
      geometry: 'box',
      provenance: { sourceType: 'ai-gen', license: 'unknown', sourceUrl: 'https://en.wikipedia.org/wiki/Night_market', confidence: 0.79 },
      performance: { polyCount: 12400, textureMemoryMB: 5.6, suggestLOD: true },
    },
    {
      id: 'obj-scanner-drone',
      name: 'Signal Scanner Drone',
      category: 'vehicle',
      description: 'Small hovering drone sweeping for rogue frequencies, amber scanner beam',
      material: 'Matte polymer, carbon fiber',
      color: '#3a3a5a',
      approx_size: '0.4m dia',
      placement_hint: 'Above center, circling antenna tower',
      importance: 2,
      source_url: 'https://cinematography.com/index.php/wong-kar-wai-neon',
      confidence: 0.76,
      position: [1, 6, -3],
      scale: [0.4, 0.2, 0.4],
      geometry: 'sphere',
      provenance: { sourceType: 'ai-gen', license: 'commercial', sourceUrl: 'https://cinematography.com/index.php/wong-kar-wai-neon', confidence: 0.76 },
      performance: { polyCount: 6200, textureMemoryMB: 3.2, suggestLOD: false },
    },
  ],
  camera: {
    shot_type: 'Handheld weave through market stalls',
    lens_feel: 'Wide-angle 28mm, slight barrel distortion, shallow DOF',
    framing_notes: 'Shoulder height, lanterns framing upper third, antenna tower anchoring deep background',
    path: [
      [0, 1.6, 8],
      [-1, 1.5, 4],
      [0.5, 1.4, 0],
      [1, 1.5, -3],
      [0, 1.8, -6],
    ],
  },
  lighting: {
    key_light: 'Warm overhead wash from LED lantern string',
    fill_light: 'Cool blue spill from dead antenna tower area',
    rim_light: 'Magenta backlight from LOST SIGNALS neon',
    practicals: ['LOST SIGNALS neon sign (magenta)', 'FREQ neon display (cyan)', 'Produce crate bioluminescence (green)', 'Drone scanner beam (amber)'],
    overall_feel: 'Warm chaos up close, cold emptiness above — saturated vendor light pools dissolving into dark signal tower silhouette',
    lights: [
      {
        id: 'light-key',
        type: 'key',
        label: 'Lantern Wash',
        color: '#ff8844',
        intensity: 1.8,
        position: [0, 4.5, 1],
        target: [0, 0, 0],
      },
      {
        id: 'light-fill',
        type: 'fill',
        label: 'Cool Tower Spill',
        color: '#4466ff',
        intensity: 0.5,
        position: [0, 7, -6],
      },
      {
        id: 'light-rim',
        type: 'rim',
        label: 'Neon Backlight',
        color: '#ff006a',
        intensity: 1.4,
        position: [0.5, 5.5, -5.5],
        target: [0, 1, 2],
      },
      {
        id: 'light-practical-1',
        type: 'practical',
        label: 'LOST SIGNALS Sign',
        color: '#ff006a',
        intensity: 1.0,
        position: [0.5, 5.5, -5.5],
      },
      {
        id: 'light-practical-2',
        type: 'practical',
        label: 'FREQ Display',
        color: '#00ffaa',
        intensity: 0.8,
        position: [3.2, 2.8, 1.8],
      },
    ],
  },
  color_palette: ['#ff006a', '#00ffaa', '#ff8844', '#4466ff', '#22aa66', '#1a0033', '#0a0a10'],
  mood_keywords: ['nocturnal', 'chaotic', 'intimate', 'signal-ghost', 'lo-fi warmth', 'neon-soaked', 'market-buzz'],
  composition_rules: [
    'Antenna tower centered as vertical anchor in deep background',
    'Lantern string creates leading line across upper third',
    'Vendor stalls frame both sides like canyon walls',
    'Haze layer separates foreground warmth from background void',
  ],
  citations: [
    { url: 'https://www.artstation.com/artwork/neon-night-market-concept', snippet: 'Open-air bazaar under tangled cables and holographic tarps' },
    { url: 'https://en.wikipedia.org/wiki/Night_market', snippet: 'Decommissioned towers repurposed as tent poles in signal-dead zones' },
    { url: 'https://www.blenderguru.com/tutorials/emissive-market-lighting', snippet: 'String lights on catenary curves + area lights inside stalls' },
    { url: 'https://cinematography.com/index.php/wong-kar-wai-neon', snippet: 'Saturated color pools from practicals, no neutral fill' },
    { url: 'https://www.turbosquid.com/night-market-props', snippet: 'Folding table stall kits, antenna mast segments, cable spools' },
  ],
};

// Artifact bank — items discovered by TinyFish that the user can drag into the scene
export const ARTIFACT_BANK: Artifact[] = [
  // Architecture / structures
  { id: 'a-stall-tarp', name: 'Tarp Stall', category: 'architecture', icon: '\u25A3', color: '#2a1a3e', tags: ['structure', 'vendor'], relatedIds: ['a-stall-metal', 'a-canopy'], gx: 0.12, gy: 0.1 },
  { id: 'a-stall-metal', name: 'Metal Booth', category: 'architecture', icon: '\u25A8', color: '#1a2a3e', tags: ['structure', 'vendor'], relatedIds: ['a-stall-tarp', 'a-antenna'], gx: 0.3, gy: 0.08 },
  { id: 'a-antenna', name: 'Antenna Tower', category: 'architecture', icon: '\u2191', color: '#3a2a1a', tags: ['structure', 'signal'], relatedIds: ['a-stall-metal', 'a-cables'], gx: 0.08, gy: 0.28 },
  { id: 'a-canopy', name: 'LED Canopy', category: 'architecture', icon: '\u25BD', color: '#ff8844', tags: ['overhead', 'light'], relatedIds: ['a-stall-tarp'], gx: 0.22, gy: 0.25 },
  { id: 'a-gate', name: 'Market Gate', category: 'architecture', icon: '\u25A1', color: '#4a3a5a', tags: ['entry', 'structure'], relatedIds: ['a-stall-tarp', 'a-stall-metal'], gx: 0.38, gy: 0.22 },
  { id: 'a-cables', name: 'Signal Cables', category: 'architecture', icon: '\u2261', color: '#2a2a3a', tags: ['overhead', 'wires'], relatedIds: ['a-antenna', 'a-canopy'], gx: 0.18, gy: 0.42 },

  // Furniture / fixtures
  { id: 'f-spool-table', name: 'Cable Spool Table', category: 'furniture', icon: '\u25CB', color: '#4a3a2a', tags: ['seating', 'repurposed'], relatedIds: ['f-crate-seat', 'f-barrel'], gx: 0.55, gy: 0.12 },
  { id: 'f-barrel', name: 'Oil Drum', category: 'furniture', icon: '\u25CB', color: '#4a3a2a', tags: ['container', 'industrial'], relatedIds: ['f-spool-table', 'f-crate-seat'], gx: 0.7, gy: 0.1 },
  { id: 'f-crate-seat', name: 'Produce Crate', category: 'furniture', icon: '\u25A0', color: '#22aa66', tags: ['container', 'glow'], relatedIds: ['f-barrel', 'f-spool-table'], gx: 0.82, gy: 0.15 },
  { id: 'f-generator', name: 'Generator', category: 'furniture', icon: '\u26A1', color: '#3a3a4a', tags: ['power', 'machine'], relatedIds: ['f-spool-table'], gx: 0.6, gy: 0.28 },
  { id: 'f-bench', name: 'Folding Bench', category: 'furniture', icon: '\u2550', color: '#5a5a6a', tags: ['seating', 'street'], relatedIds: ['f-spool-table'], gx: 0.78, gy: 0.3 },

  // Props
  { id: 'p-neon-lost', name: 'LOST SIGNALS Sign', category: 'props', icon: '\u2606', color: '#ff006a', tags: ['neon', 'signage', 'emissive'], relatedIds: ['p-neon-freq', 'l-neon-tube'], gx: 0.15, gy: 0.58 },
  { id: 'p-neon-freq', name: 'FREQ Display', category: 'props', icon: '\u223F', color: '#00ffaa', tags: ['neon', 'signage', 'emissive'], relatedIds: ['p-neon-lost', 'l-neon-tube'], gx: 0.32, gy: 0.55 },
  { id: 'p-lantern-string', name: 'Lantern String', category: 'props', icon: '\u25CF', color: '#ff8844', tags: ['light', 'overhead'], relatedIds: ['p-signal-dish', 'l-lantern-glow'], gx: 0.48, gy: 0.52 },
  { id: 'p-signal-dish', name: 'Satellite Dish', category: 'props', icon: '\u25CE', color: '#6a6a7a', tags: ['salvage', 'antenna'], relatedIds: ['p-lantern-string', 'p-radio-module'], gx: 0.42, gy: 0.38 },
  { id: 'p-radio-module', name: 'Radio Module', category: 'props', icon: '\u25A4', color: '#3a5a4a', tags: ['tech', 'salvage'], relatedIds: ['p-signal-dish', 'p-cable-coil'], gx: 0.58, gy: 0.48 },
  { id: 'p-cable-coil', name: 'Cable Coil', category: 'props', icon: '\u25CE', color: '#2a2a3a', tags: ['wire', 'ground'], relatedIds: ['p-radio-module'], gx: 0.65, gy: 0.58 },
  { id: 'p-torn-banner', name: 'Torn Banner', category: 'props', icon: '\u25AD', color: '#6a4a3a', tags: ['fabric', 'decor'], relatedIds: ['p-neon-lost'], gx: 0.25, gy: 0.72 },

  // Vehicles
  { id: 'v-cart', name: 'Delivery Cart', category: 'vehicles', icon: '\u25B7', color: '#1a3a2a', tags: ['vehicle', 'electric'], relatedIds: ['v-drone', 'f-generator'], gx: 0.82, gy: 0.48 },
  { id: 'v-drone', name: 'Scanner Drone', category: 'vehicles', icon: '\u25C7', color: '#3a3a5a', tags: ['flying', 'surveillance'], relatedIds: ['v-cart', 'l-scanner-beam'], gx: 0.9, gy: 0.38 },

  // Environment
  { id: 'e-haze', name: 'Market Haze', category: 'environment', icon: '\u2601', color: '#4a4a6a', tags: ['atmosphere', 'volume'], relatedIds: ['e-smoke', 'p-lantern-string'], gx: 0.72, gy: 0.68 },
  { id: 'e-smoke', name: 'Cooking Smoke', category: 'environment', icon: '\u2248', color: '#5a4a3a', tags: ['particles', 'atmosphere'], relatedIds: ['e-haze', 'f-generator'], gx: 0.85, gy: 0.62 },
  { id: 'e-night-sky', name: 'Dead Signal Sky', category: 'environment', icon: '\u263D', color: '#0a0a2a', tags: ['background', 'dark'], relatedIds: ['e-haze'], gx: 0.92, gy: 0.72 },

  // Lighting
  { id: 'l-neon-tube', name: 'Neon Tube', category: 'lighting', icon: '\u2501', color: '#ff006a', tags: ['emissive', 'practical'], relatedIds: ['p-neon-lost', 'p-neon-freq'], gx: 0.1, gy: 0.85 },
  { id: 'l-lantern-glow', name: 'Lantern Glow', category: 'lighting', icon: '\u25BD', color: '#ff8844', tags: ['key', 'warm'], relatedIds: ['l-neon-tube', 'l-tower-spill'], gx: 0.3, gy: 0.88 },
  { id: 'l-tower-spill', name: 'Tower Spill', category: 'lighting', icon: '\u25B3', color: '#4466ff', tags: ['fill', 'cold'], relatedIds: ['l-lantern-glow'], gx: 0.5, gy: 0.85 },
  { id: 'l-scanner-beam', name: 'Scanner Beam', category: 'lighting', icon: '\u25CF', color: '#ffaa22', tags: ['practical', 'sweep'], relatedIds: ['v-drone', 'l-neon-tube'], gx: 0.68, gy: 0.82 },
  { id: 'l-crate-glow', name: 'Crate Biolum', category: 'lighting', icon: '\u25CB', color: '#22aa66', tags: ['practical', 'ambient'], relatedIds: ['l-lantern-glow', 'l-tower-spill'], gx: 0.42, gy: 0.95 },
];

export const ARTIFACT_CATEGORY_COLORS: Record<string, string> = {
  architecture: '#7C3AED',
  furniture: '#06B6D4',
  props: '#EC4899',
  vehicles: '#F59E0B',
  environment: '#10B981',
  lighting: '#FF6B6B',
};

export const SCANNING_STEPS = [
  'Initializing research agent...',
  'Connecting to TinyFish...',
  'Launching browser session...',
  'Searching for night market references...',
  'Visiting artstation.com...',
  'Extracting market layout data...',
  'Visiting signal culture references...',
  'Analyzing vendor lighting techniques...',
  'Gathering stall and prop dimensions...',
  'Compiling scene metadata...',
  'Validating source citations...',
  'Research complete',
];

export const MOCK_VALIDATION_RESULT: ValidationResult = {
  checks: [
    { id: 'v-poly-budget', label: 'Polygon Budget', status: 'pass', detail: '55,900 / 100,000', category: 'geometry' },
    { id: 'v-uv-presence', label: 'UV Maps Present', status: 'pass', detail: '14/14 objects have UVs', category: 'uv' },
    { id: 'v-material-assign', label: 'Material Assignment', status: 'pass', detail: 'All objects have materials', category: 'material' },
    { id: 'v-non-manifold', label: 'Non-Manifold Geometry', status: 'warn', detail: '2 objects with non-manifold edges', category: 'geometry' },
    { id: 'v-tex-resolution', label: 'Texture Resolution', status: 'pass', detail: 'All textures within 2K limit', category: 'texture' },
    { id: 'v-source-citation', label: 'Source Citations', status: 'pass', detail: '14/14 objects have source URLs', category: 'provenance' },
    { id: 'v-license-check', label: 'License Compliance', status: 'warn', detail: '1 object has unknown license', category: 'provenance' },
    { id: 'v-overlap-detect', label: 'Overlapping Faces', status: 'pass', detail: 'No overlapping geometry', category: 'geometry' },
    { id: 'v-tex-memory', label: 'Texture Memory', status: 'pass', detail: '31.2 MB / 256 MB budget', category: 'texture' },
    { id: 'v-scale-uniform', label: 'Scale Consistency', status: 'pass', detail: 'All objects use metric scale', category: 'geometry' },
  ],
  passCount: 8,
  warnCount: 2,
  failCount: 0,
  overallStatus: 'pass',
  timestamp: Date.now(),
};

export const MOCK_PIPELINE_CHECKPOINTS: PipelineCheckpoint[] = [
  { stage: 1, label: 'Raw Scrape', description: 'TinyFish web research', timestamp: null, status: 'pending' },
  { stage: 2, label: 'Validated Spec', description: 'QA checks passed', timestamp: null, status: 'pending' },
  { stage: 3, label: 'Blockout Sent', description: 'Pushed to Blender', timestamp: null, status: 'pending' },
  { stage: 4, label: 'Artist Refinement', description: 'Pending artist review', timestamp: null, status: 'pending' },
];

export const MOCK_CONTEXTUAL_TIPS: ContextualTip[] = [
  { id: 'tip-1', phase: 2, message: 'TinyFish extracts structured data \u2014 every claim needs a source URL', icon: '\uD83D\uDC1F', category: 'research' },
  { id: 'tip-2', phase: 3, message: 'Artifacts with unknown licenses are flagged during validation', icon: '\u26A0\uFE0F', category: 'research' },
  { id: 'tip-3', phase: 4, message: 'SceneSpec validates polygon budgets before sending to Blender', icon: '\u2705', category: 'plan' },
  { id: 'tip-4', phase: 5, message: 'Objects use graybox primitives \u2014 swap for production meshes later', icon: '\uD83D\uDFE8', category: 'build' },
  { id: 'tip-5', phase: 5, message: 'Auto-record can change keyframes unexpectedly \u2014 disable when posing', icon: '\u26A0\uFE0F', category: 'general' },
  { id: 'tip-6', phase: 6, message: 'Practical lights should match visible light sources in scene', icon: '\uD83D\uDCA1', category: 'lighting' },
  { id: 'tip-7', phase: 7, message: 'Camera paths export as Blender animation curves via SceneSpec', icon: '\uD83C\uDFAC', category: 'general' },
  { id: 'tip-8', phase: 8, message: 'All assets tracked: scan/AI/manual/web-ref with license status', icon: '\uD83D\uDCCB', category: 'general' },
];
