import type { SceneMetadata, ResearchSource, TinyFishEvent } from './types';

export const DEMO_TOPIC = 'cyberpunk alleyway at night';

export const MOCK_RESEARCH_SOURCES: ResearchSource[] = [
  {
    id: 'src-1',
    url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
    title: 'Cyberpunk Alley Concept Art — ArtStation',
    snippets: [
      'Narrow corridor between towering megastructures',
      'Neon signage in Japanese and English, wet asphalt reflections',
      'Dense cable runs overhead connecting buildings',
    ],
    tags: ['concept-art', 'neon', 'architecture'],
    confidence: 0.94,
    thumbnail_gradient: ['#ff006a', '#1a0033'],
  },
  {
    id: 'src-2',
    url: 'https://en.wikipedia.org/wiki/Cyberpunk',
    title: 'Cyberpunk — Wikipedia',
    snippets: [
      'High tech, low life aesthetic combining advanced technology with social decay',
      'Rain-soaked streets illuminated by holographic advertisements',
      'Characteristic palette: magenta, cyan, deep purple against black',
    ],
    tags: ['genre', 'aesthetic', 'reference'],
    confidence: 0.88,
    thumbnail_gradient: ['#4466ff', '#0a0a10'],
  },
  {
    id: 'src-3',
    url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes',
    title: 'Neon Lighting in Blender — Blender Guru',
    snippets: [
      'Use emission shaders on thin geometry for neon tube effect',
      'Point lights with falloff 0.5m for localized neon glow',
      'Volumetric fog at 0.02 density for light scattering',
    ],
    tags: ['blender', 'lighting', 'tutorial'],
    confidence: 0.91,
    thumbnail_gradient: ['#00ffaa', '#0a1a10'],
  },
  {
    id: 'src-4',
    url: 'https://cinematography.com/index.php/blade-runner-lighting',
    title: 'Blade Runner Lighting Breakdown',
    snippets: [
      'Key light from above, heavily diffused, warm-to-cool gradient',
      'Rim light separates characters from background, cold blue',
      'Practical neon signs provide motivated in-scene lighting',
    ],
    tags: ['cinematography', 'film-reference', 'lighting'],
    confidence: 0.87,
    thumbnail_gradient: ['#ff6600', '#0a0a30'],
  },
  {
    id: 'src-5',
    url: 'https://www.turbosquid.com/cyberpunk-city-assets',
    title: 'Cyberpunk City Asset Pack — TurboSquid',
    snippets: [
      'Modular building sections: 3m, 6m, 9m heights',
      'Standard alley width 4-6 meters for human-scale reference',
      'Common props: dumpsters, AC units, fire escapes, cable bundles',
    ],
    tags: ['3d-assets', 'scale-reference', 'props'],
    confidence: 0.82,
    thumbnail_gradient: ['#7c3aed', '#0a0a10'],
  },
];

export const MOCK_TINYFISH_EVENTS: TinyFishEvent[] = [
  { type: 'STARTED', timestamp: 0, message: 'Run initiated — launching browser' },
  { type: 'STREAMING_URL', timestamp: 600, message: 'Browser session ready', url: 'https://observe.tinyfish.ai/session/fc-001' },
  { type: 'PROGRESS', timestamp: 1800, message: 'Navigating to artstation.com/artwork/cyberpunk-alley-concept' },
  { type: 'PROGRESS', timestamp: 3200, message: 'Page loaded — extracting visual reference data' },
  { type: 'PROGRESS', timestamp: 4600, message: 'Found 12 concept art images — analyzing composition' },
  { type: 'PROGRESS', timestamp: 6000, message: 'Navigating to wikipedia.org/wiki/Cyberpunk' },
  { type: 'PROGRESS', timestamp: 7400, message: 'Extracting genre aesthetics and color palette info' },
  { type: 'PROGRESS', timestamp: 8800, message: 'Navigating to blenderguru.com — lighting reference' },
  { type: 'PROGRESS', timestamp: 10200, message: 'Extracting Blender-specific lighting parameters' },
  { type: 'PROGRESS', timestamp: 11600, message: 'Visiting cinematography.com — Blade Runner breakdown' },
  { type: 'PROGRESS', timestamp: 13000, message: 'Extracting camera and lighting techniques' },
  { type: 'PROGRESS', timestamp: 14400, message: 'Navigating to turbosquid.com — asset scale reference' },
  { type: 'PROGRESS', timestamp: 15800, message: 'Extracting prop dimensions and placement data' },
  { type: 'HEARTBEAT', timestamp: 16500, message: 'Keepalive' },
  { type: 'PROGRESS', timestamp: 17200, message: 'Compiling scene metadata from 5 sources' },
  { type: 'COMPLETE', timestamp: 18000, message: 'Research complete — 14 objects, 5 lights, 5 sources, 89% avg confidence' },
];

export const MOCK_SCENE_METADATA: SceneMetadata = {
  project_title: 'Cyberpunk Alleyway',
  topic: 'cyberpunk alleyway at night',
  scene_goal: 'Moody, neon-lit back alley for a cinematic establishing shot',
  style_keywords: ['cyberpunk', 'noir', 'neon', 'rain', 'dystopian'],
  environment: {
    location_type: 'Urban back alley',
    time_of_day: 'Night',
    weather: 'Light rain, fog',
    mood: 'Brooding, tense, atmospheric',
    scale: '4m wide x 15m deep x 8m tall',
  },
  objects: [
    {
      id: 'obj-wall-left',
      name: 'Left Building Wall',
      category: 'setpiece',
      description: 'Towering concrete wall with exposed pipes and rust stains',
      material: 'Concrete, weathered',
      color: '#1a1a2e',
      approx_size: '1m x 6m x 12m',
      placement_hint: 'Left boundary of alley',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.95,
      position: [-4, 3, 0],
      scale: [1, 6, 12],
      geometry: 'box',
    },
    {
      id: 'obj-wall-right',
      name: 'Right Building Wall',
      category: 'setpiece',
      description: 'Shorter building with metal cladding and ventilation ducts',
      material: 'Metal cladding, painted',
      color: '#16213e',
      approx_size: '1m x 5m x 12m',
      placement_hint: 'Right boundary of alley',
      importance: 5,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.95,
      position: [4, 2.5, 0],
      scale: [1, 5, 12],
      geometry: 'box',
    },
    {
      id: 'obj-ground',
      name: 'Alley Floor',
      category: 'setpiece',
      description: 'Wet asphalt with puddle reflections and cracks',
      material: 'Asphalt, wet',
      color: '#0f0f1a',
      approx_size: '8m x 15m',
      placement_hint: 'Ground plane',
      importance: 5,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.92,
      position: [0, -0.01, 0],
      scale: [8, 0.05, 15],
      geometry: 'box',
    },
    {
      id: 'obj-dumpster',
      name: 'Dumpster',
      category: 'prop',
      description: 'Rusted green dumpster, lid half-open, overflowing',
      material: 'Painted metal, rusted',
      color: '#2d4a22',
      approx_size: '1.2m x 1m x 0.8m',
      placement_hint: 'Left side, mid-alley',
      importance: 3,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.88,
      position: [-2.5, 0.5, 3],
      scale: [1.2, 1, 0.8],
      geometry: 'box',
    },
    {
      id: 'obj-neon-ramen',
      name: 'Neon Sign "RAMEN"',
      category: 'prop',
      description: 'Flickering pink neon sign mounted on left wall',
      material: 'Neon glass tubing, emissive',
      color: '#ff006a',
      approx_size: '1.5m x 0.4m x 0.1m',
      placement_hint: 'Left wall, high',
      importance: 4,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.93,
      position: [-3.4, 3.5, 1],
      scale: [1.5, 0.4, 0.1],
      geometry: 'box',
    },
    {
      id: 'obj-neon-bar',
      name: 'Neon Sign "BAR"',
      category: 'prop',
      description: 'Cyan neon sign buzzing on right wall',
      material: 'Neon glass tubing, emissive',
      color: '#00ffaa',
      approx_size: '1m x 0.3m x 0.1m',
      placement_hint: 'Right wall, mid-height',
      importance: 4,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.91,
      position: [3.4, 2.8, -2],
      scale: [1, 0.3, 0.1],
      geometry: 'box',
    },
    {
      id: 'obj-fire-escape',
      name: 'Fire Escape',
      category: 'setpiece',
      description: 'Rusty metal fire escape zigzagging up left wall',
      material: 'Iron, rusted',
      color: '#4a4a5a',
      approx_size: '1.5m x 4m x 0.1m',
      placement_hint: 'Left wall, rear section',
      importance: 3,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.86,
      position: [-3.4, 2, -2],
      scale: [1.5, 4, 0.1],
      geometry: 'box',
    },
    {
      id: 'obj-steam-vent',
      name: 'Steam Vent Pipe',
      category: 'prop',
      description: 'Vertical pipe venting steam, creating atmosphere',
      material: 'Steel pipe',
      color: '#6a6a7a',
      approx_size: '0.15m dia x 2m',
      placement_hint: 'Right side, near entrance',
      importance: 2,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.84,
      position: [2, 1, 4],
      scale: [0.15, 2, 0.15],
      geometry: 'cylinder',
    },
    {
      id: 'obj-motorcycle',
      name: 'Motorcycle',
      category: 'vehicle',
      description: 'Parked motorcycle, dark matte finish, chrome accents',
      material: 'Metal, matte black',
      color: '#1a1a1a',
      approx_size: '0.6m x 0.5m x 1.2m',
      placement_hint: 'Right side, mid-alley',
      importance: 3,
      source_url: 'https://en.wikipedia.org/wiki/Cyberpunk',
      confidence: 0.79,
      position: [2, 0.35, 1],
      scale: [0.6, 0.7, 1.4],
      geometry: 'box',
    },
    {
      id: 'obj-puddle',
      name: 'Puddle',
      category: 'fx',
      description: 'Reflective puddle catching neon light',
      material: 'Water, highly reflective',
      color: '#1a1a3a',
      approx_size: '2m x 1.5m',
      placement_hint: 'Center of alley',
      importance: 3,
      source_url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes',
      confidence: 0.87,
      position: [0, 0.01, 1],
      scale: [2.5, 0.02, 2],
      geometry: 'box',
    },
    {
      id: 'obj-drone',
      name: 'Hovering Drone',
      category: 'vehicle',
      description: 'Small surveillance drone with red indicator light',
      material: 'Matte polymer',
      color: '#3a3a5a',
      approx_size: '0.3m dia',
      placement_hint: 'Above center, high',
      importance: 2,
      source_url: 'https://en.wikipedia.org/wiki/Cyberpunk',
      confidence: 0.76,
      position: [1, 4.5, -1],
      scale: [0.3, 0.15, 0.3],
      geometry: 'sphere',
    },
    {
      id: 'obj-ac-unit',
      name: 'AC Unit',
      category: 'prop',
      description: 'Window-mounted AC unit dripping condensation',
      material: 'Painted metal',
      color: '#5a5a6a',
      approx_size: '0.8m x 0.6m x 0.4m',
      placement_hint: 'Right wall, high',
      importance: 2,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.83,
      position: [3.4, 3.5, 0],
      scale: [0.8, 0.6, 0.4],
      geometry: 'box',
    },
    {
      id: 'obj-cables',
      name: 'Cable Bundle',
      category: 'setpiece',
      description: 'Dense overhead cable bundle connecting buildings',
      material: 'Rubber-coated wire',
      color: '#2a2a3a',
      approx_size: '8m span',
      placement_hint: 'Overhead, spanning alley',
      importance: 3,
      source_url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept',
      confidence: 0.90,
      position: [0, 5.5, 0],
      scale: [0.08, 0.08, 10],
      geometry: 'cylinder',
    },
    {
      id: 'obj-trash',
      name: 'Trash Bags',
      category: 'prop',
      description: 'Black trash bags piled near the dumpster',
      material: 'Plastic, shiny',
      color: '#1a1a1a',
      approx_size: '0.4m x 0.3m',
      placement_hint: 'Near dumpster, ground level',
      importance: 1,
      source_url: 'https://www.turbosquid.com/cyberpunk-city-assets',
      confidence: 0.80,
      position: [-2.5, 0.2, 4],
      scale: [0.5, 0.35, 0.5],
      geometry: 'sphere',
    },
  ],
  camera: {
    shot_type: 'Slow dolly through alley',
    lens_feel: 'Wide-angle 24mm, slight barrel distortion',
    framing_notes: 'Low angle, neon signs framing upper third, vanishing point deep in alley',
    path: [
      [0, 2, 8],
      [0.5, 1.8, 4],
      [0, 1.5, 0],
      [-0.5, 1.8, -3],
      [0, 2, -5],
    ],
  },
  lighting: {
    key_light: 'Overhead neon wash — warm pink from RAMEN sign area',
    fill_light: 'Cool blue ambient bounce from right wall',
    rim_light: 'Cold cyan backlight from deep in alley',
    practicals: ['RAMEN neon sign (pink)', 'BAR neon sign (cyan)', 'Drone indicator (red)'],
    overall_feel: 'High contrast, neon-soaked noir — deep shadows with vivid color pools',
    lights: [
      {
        id: 'light-key',
        type: 'key',
        label: 'Overhead Neon',
        color: '#ff006a',
        intensity: 2.0,
        position: [0, 6, 0],
        target: [0, 0, 0],
      },
      {
        id: 'light-fill',
        type: 'fill',
        label: 'Blue Ambient',
        color: '#4466ff',
        intensity: 0.6,
        position: [-3, 3, -4],
      },
      {
        id: 'light-rim',
        type: 'rim',
        label: 'Cold Backlight',
        color: '#00ffaa',
        intensity: 1.5,
        position: [0, 4, -7],
        target: [0, 1, 0],
      },
      {
        id: 'light-practical-1',
        type: 'practical',
        label: 'RAMEN Sign',
        color: '#ff006a',
        intensity: 1.2,
        position: [-3.4, 3.5, 1],
      },
      {
        id: 'light-practical-2',
        type: 'practical',
        label: 'BAR Sign',
        color: '#00ffaa',
        intensity: 0.9,
        position: [3.4, 2.8, -2],
      },
    ],
  },
  color_palette: ['#ff006a', '#00ffaa', '#4466ff', '#1a0033', '#0a0a10', '#6a6a7a', '#ff6600'],
  mood_keywords: ['noir', 'neon-soaked', 'rain-slicked', 'brooding', 'high-contrast', 'cinematic', 'dystopian'],
  composition_rules: [
    'Vanishing point centered in frame',
    'Neon signs frame upper third',
    'Leading lines from building edges guide the eye',
    'Reflections in puddle mirror upper composition',
  ],
  citations: [
    { url: 'https://www.artstation.com/artwork/cyberpunk-alley-concept', snippet: 'Narrow corridor between megastructures with neon signage' },
    { url: 'https://en.wikipedia.org/wiki/Cyberpunk', snippet: 'High tech, low life — magenta, cyan, purple against black' },
    { url: 'https://www.blenderguru.com/tutorials/lighting-neon-scenes', snippet: 'Emission shaders + point lights + volumetric fog' },
    { url: 'https://cinematography.com/index.php/blade-runner-lighting', snippet: 'Practical neon provides motivated in-scene lighting' },
    { url: 'https://www.turbosquid.com/cyberpunk-city-assets', snippet: 'Modular sections, 4-6m alley width, standard prop set' },
  ],
};

export const SCANNING_STEPS = [
  'Initializing research agent...',
  'Connecting to TinyFish...',
  'Launching browser session...',
  'Searching for visual references...',
  'Visiting artstation.com...',
  'Extracting composition data...',
  'Visiting genre references...',
  'Analyzing lighting techniques...',
  'Gathering asset dimensions...',
  'Compiling scene metadata...',
  'Validating source citations...',
  'Research complete',
];
